### ISSUE TITLE
'Source Code Policy' header link broken

### ISSUE THREAD

**Issue by lukefretwell** [WhiteHouse/source-code-policy#1]
The link goes to https://sourcecode.cio.gov/source-code-policy and looks like should go to https://sourcecode.cio.gov.

<img width="347" alt="screen shot 2016-03-10 at 7 02 11 am" src="https://cloud.githubusercontent.com/assets/1569463/13673526/324073d6-e68e-11e5-8b82-0eb2054cb9b8.png">

**Comment by chasingamy** [comment]
Thank you very much for bringing this to our attention. This link should be fixed now.
