### ISSUE TITLE
OSS as noncommercial software

### ISSUE THREAD

**Issue by ljoubert** [WhiteHouse/source-code-policy#111]
Line 377:  [**agencies need to**]

> amend any policies that are inconsistent with the requirements of this memo, including the correction of policies that automatically treat OSS as noncommercial software.

What is the purpose of this sentence? How can a policy consider OSS as noncommercial software only and what are the consequences from a government agency's perspective?

**Comment by konklone** [comment]
This may be helpful: 

http://dodcio.defense.gov/OpenSourceSoftwareFAQ.aspx#Q:_Why_is_it_important_to_understand_that_open_source_software_is_commercial_software.3F

**Comment by ljoubert** [comment]
The link is great. It shows a great difference with what we are used to in France, but I understand the logic: OSS should be considered commercial software since a non-commercial clause is not valid from an OSS license perspective. It then falls under the laws, regulations and policies for procurement of supplies and services. Thank you very much for your help
