### ISSUE TITLE
Software Procurement Considerations are ambiguous as to the evaluation of open source software

### ISSUE THREAD

**Issue by benbalter** [WhiteHouse/source-code-policy#130]
Section 3, ["Software Procurement Considerations"](https://sourcecode.cio.gov/Procurement/), states in the first step, "Alternatives Analysis", that agencies must "demonstrate a preference for the use of existing software solutions _for which the Government holds appropriate license rights or ability to reuse_" (emphasis mine). Step two "COTS solutions" then goes on to require the agency to evaluate closed, mixed, and open source software on equal footing.

I believe the authors intended that the agency first look to software already developed by the Federal government. However, any existing open source project, properly licensed to the world (the US Federal government included) under an open source license, would provide the agency with the "appropriate license rights or ability to reuse". If an existing open source project, for which the government has usage right, by virtue of its open source license, meets the government's needs, does the procurement analysis conclude?

Further confusing the issue, what happens if an open source project has been previously contributed to by the government, and thus is at least in part, taxpayer funded? Should that project get preference? What if, although started by citizens, through contributions, it is 50%+ government created at the time of procurement? What of a project started by the government that receives 50%+ community contributions? If the government has usage rights to a piece of software, why does code visibility or external contribution influence the procurement analysis?

If "existing software solutions for which the Government holds appropriate license rights or ability to reuse" includes open source software, is open source software given a priority in procurement? If not, what is the rationale for excluding open source software from that definition?

**Comment by rebeccawilliams** [comment]
I strongly agree with this clarifying point. This policy should encourage the use of all kinds of legally reusable software whether or not the code was originally created by the Federal Government or not. Moreover, any tendency, interpretation, or rationale behind this policy that is based primarily on the government reusing government code should be clarified to a broader open source preference. The purpose of this policy is for the Federal Government to be an active participant (giver and receiver) in the larger open source ecosystem for a [wide range of detailed benefits](https://github.com/WhiteHouse/source-code-policy/issues/90#issuecomment-207820011).
