### ISSUE TITLE
GSA IT: Code Reviews for Quality

### ISSUE THREAD

**Issue by nvembar** [WhiteHouse/source-code-policy#134]
The following is from GSA IT as a whole:

In addition to code reviews for security, it would also be useful for OMB to indicate that those code reviews occur as part of the normal matter of course so that the code released is well-documented and understood in order to gain the best feedback from the community.

**Comment by jlberryhill** [comment]
Thanks, @nvembar! Would you agree, @GSA-CIO-das?
