### ISSUE TITLE
Feasibility of the OSS pilot and caveats to consider

### ISSUE THREAD

**Issue by CGIFederalInc** [WhiteHouse/source-code-policy#139]
OMB has enumerated concerns regarding the feasibility of the OSS pilot approach. As noted on several previous discussion threads, open source software helps lower costs with OSS reuse. It also supports most operational and mission needs of covered agencies. Some thoughts on the feasibility of the pilot approach:

Lower costs with OSS reuse:
- Duplicative efforts are eliminated resulting in cost savings
- Community reviews and contributions lead to higher quality software reducing operations and maintenance cost
- OSS must be carefully selected. Procurement of OSS production support can offset cost savings.
- Successful OSS projects enjoy long-term viability and economical support plans
- Indirect costs associated with implementation of OSS can be higher than those associated with COTS. Examples include staff training, change management, and updates and replacement.

Meet operational and mission needs of agencies:
- Successful OSS projects are generally well designed and documented
- Vendors have reason to establish processes that assure higher quality of source code
- Application Lifecycle Management (ALM) tools achieve higher productivity, transparency, and software quality

Here are some caveats to consider when implementing the pilot:
- 20% of custom code to be made open source is a difficult expectation
- Open by default is attractive, but does not mean all open source software is reusable
- Qualification of return of investment is a challenge
- Cutting corners in code quality is not an option – even with a time crunch
- Reuse does not mean contribution. Contribution is essential to OSS success
- Funding model for OSS is paramount to success. OMB should issue guidance for the same
- OMB must issue OSS licensing guidance. OMB should consider creating a new license and should get it approved by the Open Source Initiative (OSI) like most widely used OSS licenses.

**Comment by JoshData** [comment]
> OMB should consider creating a new license and should get it approved by the Open Source Initiative (OSI) like most widely used OSS licenses.

+1 if this was intended as a joke.

**Comment by dysinger** [comment]
I will also have this opinion for $200 million.  Sign me up.

**Comment by eads** [comment]
Worth noting there are existing models for agency/site/govt specific licenses that are OSI compatible such as the [Fermitools license](https://cdcvs.fnal.gov/redmine/projects/fermitools/wiki). 

The 2 and 3 clause BSD licenses are specifically designed to cover this use-case without having to write another license from scratch.
