### ISSUE TITLE
[meta] Consider extending the comment period?

### ISSUE THREAD

**Issue by benbalter** [WhiteHouse/source-code-policy#155]
Given that in the past 24 hours, there have been substantial new discussions opened by major stakeholders, including [OSEHRA](https://github.com/WhiteHouse/source-code-policy/issues/153), [Department of Homeland Security Office of the Chief Information Officer and Components](https://github.com/WhiteHouse/source-code-policy/issues/152), [Air Force Office of the General Counsel](https://github.com/WhiteHouse/source-code-policy/issues/151), [Institute for Defense Analyses](https://github.com/WhiteHouse/source-code-policy/issues/150), [Creative Commons](https://github.com/WhiteHouse/source-code-policy/issues/149), [Council on Governmental Relations and the Association of American Universities](https://github.com/WhiteHouse/source-code-policy/issues/148), [Red Hat](https://github.com/WhiteHouse/source-code-policy/issues/146), [BSA](https://github.com/WhiteHouse/source-code-policy/issues/144), [eCPIC](https://github.com/WhiteHouse/source-code-policy/issues/143), and [GSA IT](https://github.com/WhiteHouse/source-code-policy/issues/134), would OMB consider extending the comment period to allow interested parties the necessary time to read, review, and if appropriate, reply to these new comments? 

Many of these last-minute comments raise critical points not already contained in previous discussions, and I believe that to allow these comments to be memorialized in the official record unanswered would be a disservice to OMB's goals of fostering a thorough and substantive discussion as to the merits of the proposed policy, and would go contrary to the spirits of open source and the open collaboration that the policy ultimately seeks to foster.

Specifically, I'd respectfully like to request that OMB considers extending the comment period by exactly one week to allow only reply comments (e.g., replying to existing issues, rather than opening new issues or pull requests).

**Comment by johnmod3** [comment]
@benbalter I just thought the same thing +1

**Comment by konklone** [comment]
A big :+1: to extending the comment period, given the deluge of substantive comments posted in the last 24 hours. I know 18F definitely benefited from thoughtful responses to its own comments (such as #87), and we suspect the public and OMB benefited from that as well. We would also appreciate the opportunity to review recent comments, and address any novel points as is constructive.

> Specifically, I'd respectfully like to request that OMB considers extending the comment period by exactly one week to allow only reply comments (e.g., replying to existing issues, rather than opening new issues or pull requests).

One week would probably be fine, though two is easier -- and I wouldn't put technical constraints on opening new issues, if that ends up making more sense than extending a discussion.

**Comment by gbinal** [comment]
_[Speaking in my personal capacity]_

I heartily concur with this.    Please extend the comment window to allow responses to the substantive responses that have been posted at the 11th hour.

**Comment by tvol** [comment]
:+1: agree with the above so interested parties can provide feedback on the responses.

**Comment by konklone** [comment]
Just noting that OMB did extend the comment period by 7 days in #183:

> Many thanks to everyone who has provided feedback throughout the last month.
> 
> The public comment period has been extended by 7 days. The new deadline for public feedback is April 18, 2016.

**Comment by JJediny** [comment]
+1 on the extension - hope to be able to do #117 justice over this next week. See related #116

**Comment by planspark** [comment]
FYI, looks like the comment period has just been extended as per [#183](https://github.com/WhiteHouse/source-code-policy/issues/183).
