### ISSUE TITLE
Email Comment: This should have been done long ago

### ISSUE THREAD

**Issue by OMBPublicComments** [WhiteHouse/source-code-policy#156]
[Email Comment, received on 4/11/2016 at 3:40PM ET]

I am shocked that all government-written or government-purchased software _hasn't_ been available to the public under free software licenses or as public domain. It's public money! 
## 

Robin 'Roblimo' Miller
Bradenton, Florida, USA
- Freelance writer & videomaker
- Member, Internet Press Guild
- Member, American Legion

**Comment by murpup** [comment]
Yes it is public money, but there are historically valid reasons for the government having operated the way it has.  

If the government has paid to have some software developed, it almost always maintains the right to use or modify that software product for its own purposes however it wants.  So in that sense, the public is deriving value from its tax dollars.  But in the past, as part of the contracting process, what the government has done is to give up its right to redistribute the software by allowing the contractor to copyright the software for itself.  This approach can have certain benefits:

a) it incentivizes companies to bid on government contracts, thereby enhancing competition and helping the government to get a better price,

b) it allows companies to develop their own intellectual property which then helps them to grow and become more competitive in the marketplace.  Many would argue that one of the functions of government is to help stimulate and grow the economy.

c) Businesses would argue that they are taxpayers too and that it is not the role of government to essentially be in competition with private business.

d) by letting businesses copyright the software, it may help to prevent other countries from just taking American-developed intellectual property and using it to compete against our own businesses in the global marketplace.  Of course, in this day and age of globalization and multinational corporations, that argument has less punch.

You may take issue with the above points, and would likely be correct, but in my experience, those are, at least, some of the justifications for why the government has historically operated the way it has. I favor a more open approach in general, myself.
