### ISSUE TITLE
Comments from New America's Open Technology Institute

### ISSUE THREAD

**Issue by oti-tech** [WhiteHouse/source-code-policy#172]
[New America’s Open Technology Institute](https://newamerica.org/oti/) (OTI) is extremely appreciative of the opportunity to provide feedback to the OMB regarding the Draft Federal [Source Code Policy](https://sourcecode.cio.gov/). We applaud that the White House is looking at impediments to deploying free software, and not whether such software is appropriate for government use.
### Licensing

As an organization dedicated to universal access to communications technologies that are both open and secure, OTI fully supports the White House’s effort to increase the use of Open Source Software (OSS) in government, and an assertion that Free and Libre software (F/LOSS) should be placed on an equal footing with open source software in this policy. 

Recognizing that licensing is a contentious issue, with long standing debates, there is a significant a body of work under the banners of both Free Software and Open Source Software. This policy would benefit from clear definitions of both, [as well as the use of inclusive terminology such as FOSS/FLOSS instead of OSS](https://github.com/WhiteHouse/source-code-policy/issues/92), which may otherwise exclude the use of free/libre licenses.

OTI agrees with recommendations that the OMB refrain from creating its own open source license, and rather curate a list of existing Free and Open Source licenses that comply with OMB’s standards. The creation of a license unique to government would interfere with the draft policy’s goal of industry acceptance and code reuse. It would also make it more difficult to build and maintain communities around a given code-base.
### Open by Default

The Open Technology Institute [supports](https://github.com/WhiteHouse/source-code-policy/issues/90) a policy of “open by default” as being closest to the spirit of making government works available for public use. An “open by default” policy will have a positive long-term impact on the software development market. Open Source has clear transparency advantages: allowing the code to be viewed and studied, promotes code robustness, adherence to code quality standards, and allows vendors to tailor their bids to match or exceed the standards of existing code. 

It can even be argued that F/LOSS code is more easily secured. While this is a topic of some disagreement, it is undeniable that Open Source provides an opportunity for NGOs and interested citizens to audit code in an effort to make government services more effective, efficient and reliable. Parties who are not the vendor can fully audit code to make sure that it does in fact adhere to OMB’s highest technical and security standards.

Open source code makes programmer time more effective and efficient. With more code made available for reuse, there is greater likelihood for cost and time-saving opportunities for the federal government, as well as increased quality control.

Additionally, we agree that metrics should be included as baselines for measuring the adoption and effectiveness of these policies. However, the ["20 percent"](https://github.com/WhiteHouse/source-code-policy/blob/3078617b06a1e0f3847eebd8a8167f5aef90d70c/pages/oss.md#L26) metric for open source code release should be seen as a minimum, with the goal being as close 100% as feasible.
### Policy Scope

OTI echoes the [concerns](https://github.com/WhiteHouse/source-code-policy/issues/30) highlighted related to the TPP, and would like to see clarification as to what the interaction of this policy and the TPP is. 

While OTI recognizes that there will be cases in which national security requires that code developed by or for the government be kept secret (under 44 U.S.C. § 3542), we recommend that such instances be narrowly drawn and not encompass entire categories of software. For example, a policy that closes the source of every piece of software created for the Central Intelligence Agency (CIA) or National Security Agency (NSA) would be unduly restrictive. Keeping the source of a particular piece of software that would reveal sources or methods of intelligence gathering, on the other hand, may – in the right circumstances – be appropriate. Where possible, sections of code that can be separated from code that must remain secret and be released separately, should be.
### Commitment to Community

Alongside the government’s commitment to open source through the work of this policy and other policies, OTI urges that similar commitment be paid to the accessibility of the communities around open source projects. In particular, we recommend that all code, comments, issues, and documentation produced by the government should follow [best practices](https://github.com/gembarrett/coconduct-builder/blob/master/resources.md) and include a Code of Conduct to ensure fair representation of all contributors to work that falls under the policy.
### Long term viability

Computer code should be handled similarly to other digital assets and given the same privileges of long-term storage. The storage policy for open source programs written for the federal government should ensure independence and resilience. OMB should not rely on a particular vendor for long-term storage, and instead should extend the [data retention policy](https://www.whitehouse.gov/privacy#section-340861) of the [Presidential Records Act](http://www.archives.gov/about/laws/presidential-records.html), or author a policy that stores code in the Library of Congress or other national archive, to ensure that this public good remains available and independent of commercial providers. This is not to say that Government should not use existing services like GitHub, but rather, should establish other analogous repositories so that a company like GitHub does not become a single point of failure for the ecosystem.

New America's Open Technology Institute
github: https://github.com/opentechinstitute/
Contributors: @natmey, @jheretic, @salarcon215, @rschulman, @gembarrett, @georgiamoon

**Comment by gembarrett** [comment]
+1
