### ISSUE TITLE
By project or contract would be best way to measure 20% of open source code

### ISSUE THREAD

**Issue by smileytech** [WhiteHouse/source-code-policy#176]
_(I'm Russell, an IT Project Manager with [USAGov](https://www.usa.gov/explore), part of the General Services Administration's Office of Citizen Services and Innovative Technologies.  This comment reflects only my views and may not reflect those of GSA)._

This relates to issues #47 and #73.

I agree that ideally the default would be to open source all code developed by the federal government wherever feasible.  However, I understand why that may be difficult to implement at first, as folks become more accustomed to working out in the open, even during development.  And, if there isn't consensus around making it the default, I think the pilot approach is a good way to introduce that culture shift gradually across government.

With that said, I think the better way to measure the amount of open source code released is by measuring against complete projects, applications, or systems instead of just raw code metrics, such as lines-of-code.  There are several reasons for this:
- In general, I'd argue that the probability of open source having a positive impact is much greater if complete applications of working code is released as opposed to just partial sections of applications (say an individual module). 
- Metrics based around the amount of code are fungible at best, since things such as language, comments, and programmer style and skill can dramatically affect the lines of code required for a solution.
- Releasing full systems or applications makes it potentially easier for agencies to incorporate feedback from the community, since there won't be a concern of closed-source code having a dependency on a portion that's been open-sourced that the open source community would not know about.

Another option might be to judge this metric by contract actions awarded that require development to be open source since the 20% is specifically targeted at vendor-generated custom code (much like there are targets for contracts awarded to small businesses, etc...).

**Comment by david-a-wheeler** [comment]
I agree that "lines of code" is a relatively useless measure.  However, not all contract actions are the same; some are large, and some are tiny.

I suggest using _dollars_ spent on development as the measure.  We already have to measure dollars, indeed, we have entire accounting systems for it.

Also, there's no conflict between "release as OSS by default" and "20%"; I advocate doing both.  The "OSS by default" is, as noted, the better approach, but the 20% will help deal with PMs who want to stay in the 1980s (it provides a level of accountability).
