### ISSUE TITLE
Quality of inventories given the proposed timeline

### ISSUE THREAD

**Issue by jhourcle** [WhiteHouse/source-code-policy#186]
(All statements below are my own personal opinions, based on my experience.  They should not be considered statements by my place of work, which has not vetted this.  I have 20+ years of experience working in IT, with the last 12+ years at a federal agency.  Over the last decade, I have been heavily involved in 'inventory' (cataloging) efforts for scientific data, and have attended some discussions of software inventories such as last year's NSF funded [Software & Data Citation Workshop](https://softwaredatacitation.renci.org).  Due to issues regarding such inventories, I got a Master's degree in Information Management.)

Summary : 

I think your schedule is problematic.  The short time frames will lead to agencies putting out something that may meet the requirements, but will most likely be of questionable quality.  As such, you should also prepare for a system that can handle contributed corrections.

Explanation:

Asking people to create an inventory is problematic, as for these inventories to be useful, you need to spend sufficient time to define terms so that each group is cataloging the same concept and to build a useful schema to ensure that the catalog meets the intended purpose.  Without these efforts, such a catalog doesn't save time by enabling software re-use; it simply wastes people's time with yet another poorly conceived unfunded mandate -- both by trying to meet nebulous requirements, and then wastes the citizen's time if they try to use it without realizing just how bad the inventory actually is.  ([Like with data.gov](http://adsabs.harvard.edu/abs/2013AGUFMPA31A1822H)).

Unless you already have a schema prepared, there is no conceivable way that you will come up with a useful data model in the time that's been allotted.  Part of the problem is that 'software' can be a rather nebulous term ... it's like 'book' in the library community or 'data set' in the scientific community.  If you ask two people to inventory these items, you could come back with dramatically different sets of records -- both in terms of their number and their scope.

Let's take a quick look at the concept of 'book':  it could be the abstract creative work (eg, 'Hamlet'), an expression of that work ('Hamlet, translated to modern English' vs. 'Hamlet, in the original English'), a manifestation of that work ('Hamlet (Shakespeare Made Easy) in paperback' vs. 'Hamlet (Shakespeare Made Easy) in library binding'), or a physical item (we have 10 copies of 'Hamlet' from various printings).  (for more details, see [the 1998 IFLA report Functional Requirements for Bibliographic Records](http://www.ifla.org/publications/functional-requirements-for-bibliographic-records)).

I've given various presentations on the issue as it relates to data ... over seven years ago, I gave a talk on 'Data Relationships: Towards a Conceptual Model of Scientific Data Catalogs' to try to get the conversation started ... but it fell flat, as there were too many [polysemous terms](https://www.youtube.com/watch?v=oSWyg_RbqG8).  It took a couple of years to try to [document the terminology](http://virtualsolar.org/vocab) necessary to discuss the data & systems we were cataloging.

In many ways, software is another [unruly and poorly bounded object](http://dx.doi.org/10.2218/ijdc.v6i1.183) -- if we're lazy, we may document a project as a whole ... even when it's really composed of a server component and multiple clients to use that service in different languages.  If we have a modular system, do we document the project as a whole, or each of the modules that were developed?

The lack of a clear definition of what needs to be inventoried makes the 20% requirement next to worthless -- an agency could count 5 small modules from a single project that were open-sourced and had 4 releases, while rolling up another 80 projects that weren't released as single entries.  Should this qualify as 20% released, or 1.2% released?

Could an agency open source the modules of a project (that are useless on their own) while keeping the main project unreleased, and be able to claim they released more than 90% of the project, even when the main core was 80% of the lines of code & man-hours?

...

There are also some ambiguities in what exactly qualifies as 'Custom Code' that must be cataloged.  There are a number of projects that federal agencies fund that may not be specifically for software services, but that produce custom software as a significant portion of the effort on that project. 

I know of multiple scientific investigations that develop new systems to manage their data pipelines and archiving; I've heard of efforts where the science team developed their own databases from the ground up, rather than base their system around existing software.  In some cases, portions of the system may have been novel or at the very least needed to be customized for their investigation, but in many cases the software is a complete waste of tax payer's money, as there were multiple well-supported projects that could have accomplished their needs with only minor customization.

The federal government is then stuck with continuing to fund maintenance and further development of these boondoggles.  As such, I would like to ensure that this software is included in the inventory, rather than for there to be loopholes to avoid listing it.  As it stands how, if the contacting group funds 1% of the development, it wouldn't qualify as 'fully funded by the Federal Government'.

We must also ensure that these 'Raines' Rules' also apply to grantees and contractors receiving Federal funds moving forward.   

...

These questions about the scope of what needs to be inventory should be answered _before_ the cataloging is done, or you'll end up with groups rushing to complete a poorly defined task, and creating an absolutely worthless result.  The current schedule provides no time for agencies to seek clarification to ensure that they are all working from the same definitions.  

As it stands, the current draft requires all agencies to have their work done within 90 days of the policy's publication.  Near line 344:

> Within 90 days of the publication date of this policy, each covered agency must update, and thereafter keep up to date, its inventory of agency information resources (as required by OMB Circular A-130) to include an enterprise code inventory that lists all custom code developed for or by the agency after the publication date of this policy.

That 90 day deadline is even more troublesome when we consider that for a policy about software re-use, and its importance for efficiency won't actually have the tools released  to help them complete this task until the timer has already started.  Near line 324:

> Within 90 days of the publication date of this policy, the Administration will launch Project Open Source, an online repository of tools, best practices, and schemas to help covered agencies implement this guidance.

The required schema will luckily be released before that date.  Near line 356:

> Covered agencies must describe projects within the inventory using extensible metadata that will be described in an inventory schema on Project Open Source.  OMB will provide this inventory schema to covered agencies within 60 days of the publication of this policy.

... but this still might mean that they only have 30 days from the release of the schema until the inventory must be completed.  If you're lucky, they'll spend two weeks trying to really understand the schema and its implications, and another two weeks trying to catalog everything.  

More than likely, they'll just send out an e-mail to some upper-level management folks, and tell them that this needs to be done ... where it'll trickle down to whatever lower level management folks who will try their best to fill out the form, assuming they aren't on vacation, at a conference, or trying to deal with some emergency that's come up ... in which case, they'll spend 5-10 minutes to fill out the form.  If it's the later, we'll end up with yet another poorly cataloged, woefully incomplete system like data.gov.

...

So, I would recommend at the very least that the 90 day timer for the agencies to complete their inventory not be tied to release of the policy, but to the release of the schema and tools from OMB.  Ideally, there would be time for some sort of discussion between the agencies of any shortcomings of the schema and time for refinement before they attempt to catalog their software.

I would actually recommend that there be at least two passes in developing the schema -- because until it is built and populated, you don't know how people might attempt to use it.  It's also quite likely that any ontology or other classification system that is developed will need to be adjusted to provide for an appropriate level of detail to allow people to find candidates for software that they might be able to re-use ... if you end up with 50% of the software in the same category, it's a sign that maybe you need to deepen that category.

...

No matter what you do, you're going to want a system that allows for future maintenance, as whatever gets cataloged will be wrong.  Maybe by accident because someone didn't understand the instructions, or just because of management not knowing every little script that people develop to help them get their job done ... or because things just change with time.  Some of this might come from the top-down, but it's really the people who are trying to use the catalog who are the best experts at what is or isn't a good record.

I would also recommend that you prepare in advance for submissions from the bottom -- there are a lot of people out there who would've liked for their data to have been listed on data.gov, but the top-down system made it impossible for us to figure out how to get it included.  I suspect that similar things would happen with software -- there are quite a few things that people are proud to have written, and would love for other people to use ... but that management might not be aware of.  Being able to gauge interest in unreleased projects would help agencies better prioritize software release processes.

Some of it might be stupid stuff (eg, at least two of us hacked up replacements for 'finger' when our agency switched from x500 to LDAP), but like I mentioned in my other post, I have other programs such as for working w/ cron and mod_security logs that other people have expressed interest in.

(and, once again, I've not had any of this vetted by anyone at my work .. nor anyone else, so I apologize for any typos / spelling mistakes / occasional rambling / stuff like that.)

**Comment by murpup** [comment]
While I don't him, let me just say that, based on this comment, Mr Hourcle just "gets it" and has a deep understanding of how policies like this get translated into use within the real world.  Ignore his advice at your peril.

**Comment by sheepeeh** [comment]
> So, I would recommend at the very least that the 90 day timer for the agencies to complete their inventory not be tied to release of the policy, but to the release of the schema and tools from OMB. Ideally, there would be time for some sort of discussion between the agencies of any shortcomings of the schema and time for refinement before they attempt to catalog their software.

I (personally!) think this is a very good idea. Metadata is only useful if it is standardized. It would be much better to start with a draft schema, than to start with something homegrown and try to make it comply with the schema later on. There should also be some accompanying controlled vocabularies (nothing huge!) and content rules to help ensure quality data. E.g. all dates should be entered the same way.
