### ISSUE TITLE
Email Comment: Comments from the Free Software Foundation (FSF)

### ISSUE THREAD

**Issue by OMBPublicComments** [WhiteHouse/source-code-policy#191]
[Email Comment, received on 4/11/2016 at 11:49PM ET]

To the OMB Office of the Federal Chief Information Officer:

For over thirty years, the Free Software Foundation (FSF) https://fsf.org has defended the freedoms of computer users, primarily by making sure that all the software and documentation they use is licensed under terms that are free "as in freedom," not price.

We think the proposed Federal Source Code Policy could be a tremendous step in the right direction for the United States. It would set an example for other countries as to how the government of a free society can use technology while still respecting the freedoms of its citizens, and it would position the US at the leading edge of technological development.

Free software benefits government, and it benefits the government's people. The mission of government is to organize society for the freedom and well-being of the people. Proprietary, non-free software tramples the freedom of users; this is a fundamental social problem that government should be opposed to. Freedom means having control over your own life. If you use a program to carry out activities in your life, your freedom depends on your having control over the program. You deserve to have control over the programs you use, and all the more so when you use them for something important in your life.

As such, government needs to insist on free software in its own computing for the sake of its computational sovereignty. All users deserve control over their computing, but government has a responsibility to the people to maintain control over the computing it does on their behalf. Most government activities now depend on computing, and its control over those activities depends on its control over that computing.

This is reason enough to have all software used in government be free software. But free software can also enhance government operations, cut costs, and spur innovation:
- As we saw recently with Volkswagen, which used proprietary software
  to fool EPA regulators for years, all software can be doing
  something very different under the hood than what it claims to be
  doing. This presents ongoing risks that can undermine government
  operations in many ways, including national security. Mere audits or
  transparency are not enough here; government also needs the freedom
  to fix problems or hire a vendor different from the original one to
  do so.
- Free software is not automatically free as in price – people are
  often paid to write it, and somebody has to be paid to maintain it.
  But the kind of artificial cost inflation encouraged by proprietary
  software can be avoided. The ability to choose between many vendors
  to work on any given software platform nearly always leads to lower
  prices, while encouraging entrepreneurs to innovate and develop new
  offerings.
- Free software is at the forefront of innovation. The free software
  program Linux is at the core of Android and of the GNU/Linux
  operating system. Android is now the most widely used general
  purpose operating system in the world (unfortunately it is often
  distributed along with proprietary software, but the base operating
  system is free), and GNU/Linux powers the majority of servers on the
  Internet (and an increasing number of personal and employee
  computers). It is not an exaggeration to say that free software is
  the reason we have mobile computing at all. Another example is
  WordPress, which is free software that powers 25% of all Web sites.

Given the benefits of free software and the potential impact of this policy, we do have suggestions for improvement:
- We strongly urge you to recognize and include free "as in freedom"
  software in the policy, not just open source. New York City's Free
  and Open Source Software Act
  (http://benkallos.com/legislation/introduction-366-2014-free-and-open-source-software-act)
  is a good example of how to do this. The policy should include the
  Free Software Definition
  https://www.gnu.org/philosophy/free-sw.html and the FSF's license
  list https://www.gnu.org/licenses/license-list.html. As the home
  of the world's most widely used free software license, the GNU
  General Public License, the FSF's resources in this area have
  longstanding significance for developers and companies. The omission
  of the Free Software Definition is conspicuous and risks sending a
  negative, exclusionary signal to many developers who identify with
  that description, as well as creating unnecessary confusion about
  what is allowed by the policy. Including the term "free software" is
  also important for emphasizing freedom, indicating that this policy
  is designed to protect the autonomy of government and the rights of
  its people.
- While releasing 20% of custom code each year is a start, we
  recommend the government realize its commitment to the combination
  of transparency, participation, and collaboration by ultimately
  releasing all code as free. This requirement should be extended
  across all agencies.
- Free documentation should be added as an explicit goal of the
  policy. Good training is key to the successful deployment and use of
  any new software. Documentation is also essential for enabling
  developers who didn't originally write the software to make changes
  to it. If there is no explicit requirement for free documentation,
  vendors could continue to hold the government and users hostage by
  controlling and restricting distribution of the documentation for
  the software. The licensing requirements and definitions for free
  documentation are essentially the same as for software – Users must
  have the ability to use it how they wish, modify it, and share it.
- In addition to the federal government setting a goal to itself use
  more free software, the government should make a commitment to stop
  requiring or recommending the use of proprietary software. Saying
  that a citizen has to interact with government services using Adobe
  Reader only, or a particular company's proprietary JavaScript
  embedded on a government Web page (like regulations.gov), is akin to
  only allowing engagement from people wearing Nike sneakers.
- Lastly, we want to caution against a reliance on Github. Although
  many free software contributors are on Github, it has problems such
  as the use of proprietary JavaScript. Government should not defeat
  the benefits of distributed free software development by becoming
  reliant on a single Web site operated by a single for-profit
  company. Most importantly, use of Github should not be required to
  participate in government projects. We have criteria that may be
  helpful in evaluating code hosting sites at
  http://www.gnu.org/software/repo-criteria.

We hope that the policy will be adopted with the above improvements.
It has been exciting to see so many moves toward free software in the executive branch and across the federal government the last several years. Adopting this policy makes sense as a way to codify the goals behind those moves. We stand ready to help make sure the policy is a success, by highlighting it and encouraging members of the free software movement to participate. Thank you for the opportunity to comment.

John Sullivan, Executive Director
Free Software Foundation
+1 617 542 5942

**Comment by MinimaxHeadroom** [comment]
For reference, the above comment has also been published [on the FSF's website](https://www.fsf.org/licensing/fsf-comment-on-proposed-u-s-federal-source-code-policy).

See also the Foundation's [follow-up blog post](https://www.fsf.org/blogs/community/u-s-federal-source-code-policy-fsf-supports-and-urges-improvements-comment-by-april-18) for additional background, along with a brief outline of their proposed policy improvements.
