### ISSUE TITLE
Email Comment: NRC Staff Comments on Draft OMB Source Code Policy

### ISSUE THREAD

**Issue by OMBPublicComments** [WhiteHouse/source-code-policy#194]
[Email Comment, received on 4/12/2016 at 8:59AM ET]

The public comment period for the draft OMB policy entitled “Federal Source Code Policy – Achieving Efficiency, Transparency, and Innovation through Reusable and Open Source Software” presented the NRC Staff with an opportunity to take a closer look at the policy.  While reviewing the draft policy during the public comment period, the NRC Staff identified a few comments that it wanted to offer to OMB for its consideration.

Overall, the NRC Staff agrees that there are many opportunities to leverage open source software and utilize the future online repository of tools, best practices, and schemas to be created under Project Open Source.  The NRC Staff also agrees that utilizing open source software can yield significant benefits.

Comment 1:
To ensure consistency with existing law and executive orders covering the release of information, the NRC Staff respectfully requests that the draft policy be revised to include the following two sentences after “agencies policies.” on page 3, line 79: “In addition, source code that is prohibited from public release under the Atomic Energy Act (Restricted Data) or Executive Order 13526 (Classified National Security Information), or is controlled under Executive Order 13556 (Controlled Unclassified Information), is exempt from the requirements of this policy.  This exemption only covers cases where the source code itself is controlled, and not cases where the source code may be used to process controlled information but the source code itself is not sensitive.”

Inclusion of the proposed language would serve the purpose of the “Exceptions” process and criteria included later in the draft policy.  Under the existing construct in the draft policy, the CIO would be required to make a documented decision not to release classified information that the agency is prohibited by law from releasing.  For non-classified, sensitive information, the current construct in the draft policy will probably result in withholdings that are similar in practice to the implementing regulations for Executive Order 13556 (for Controlled Unclassified Information).  Creating a separate approach with separate criteria for deciding on the release of information (source code) will, however, create additional expense and introduce the likelihood of inconsistent interpretation and application that would be avoided by simply referencing the existing standard.

Comment 2:
The NRC Staff identified the following areas of uncertainty related to the pilot program requiring covered agencies to release at least 20 percent of their newly developed custom code annually and the release of all new custom code developed by Federal employees at covered agencies as part of their official duties (with limited exceptions).  
o   The 20 percent metric needs to be based on some unit of custom code.  The simplest reading is that all releases (minor or major) of 20 percent of custom code applications are to be made public.  In this case the unit of custom code is the application.  Other potential units of custom code include: (1) some measure of the volume for code (e.g. the number of lines of code); or (2) every release of any version of any custom code application.  Providing clarity that the intended unit of custom code is the application would simplify compliance, reporting, and monitoring.  
o   The definitions of “custom code,” “software,” and “source code” are written to be broad and inclusive.  As such, there is no indication that a de minimis test is allowed by the policy.  Some uncertainty exists as to whether short, non-complex, routine coding could be swept into the formal tracking and reporting system that the policy establishes.  If this were to happen, it could increase the cost of compliance while making it more difficult to actually identify and reuse the type of software that would result in improved efficiency and effectiveness across the government.  Providing clarity on the use of a de minimis test based on the size, complexity, or cost of covered custom code could be beneficial.

Comment 3:
Page 11 of the draft policy states: “OMB’s Office of Federal Procurement Policy (OFPP) and the U.S. Digital Service (USDS) will update the TechFAR Handbook to highlight how agencies can go about securing Federal reuse rights and open source licenses as part of their acquisitions processes.”  The NRC Staff has concerns about the 90-day deadlines contained in the draft policy given that agencies will not have the benefit of receiving an updated TechFAR Handbook beforehand.

**Comment by jackiekazil** [comment]
Can you clarify who NRC is in this?

**Comment by chasingamy** [comment]
@jackiekazil These comments came in from the U.S. Nuclear Regulatory Commission.

**Comment by jackiekazil** [comment]
Thank you!
