### ISSUE TITLE
Open, *Standard*, Machine-Readable Data

### ISSUE THREAD

**Issue by OwenAmbur** [WhiteHouse/source-code-policy#196]
Separation of concerns should be supported in open source software projects, each of which should create &/or manipulate data that is not only machine-readable but also complies with the applicable standards for the business records in question.  Software should be malleable, fungible, and relatively transitory whereas records should be persistent and usable across software systems over time.  The requirements for the business records should drive development but also be independent of any particular software code, open source or otherwise.  Open source code that fails to comply with the applicable data standards amounts to yet another "proprietary" data stovepipe.

**Comment by xmlwerks** [comment]
Agree. So, for the academics I worked for, funded by an NSF grant, schemas and Semantic markup and so forth. And this was very challenging. As Niklaus Wirth said, Data structures + Algorithms. The two are rather bound to each other. Data formats also change like fashion. So now the expectation is that open data will look like JSON objects. The provenance of data is also essential -- how was it collected, where the instruments collected accurate, were the operators trained. 

Above all else, I think we are attempting to insure public confidence.  As more and more of government  utilizes data, makes decisions by data, the public must be able to trust that the methodologies are rigorous - but not incomprehensible. The public also needs data skills.

**Comment by danbernier** [comment]
I think whether it's JSON or XML (or YAML or CSV) matters much less than describing clearly & thoroughly what the nouns are, what properties they have, how they relate to each other. That's the crucial part, and the hard part to figure out. A data dictionary would be great; if the data is in XML or JSON, use XML schemas or JSON schemas.

Parsing JSON, XML, YAML, and CSV is easy - there's already a library in your favorite language that'll parse it. (That said, _please_ make all data formats in something like JSON, XML, YAML, or CSV - a format for which there's already a library in your favorite language that'll parse it.)

**Comment by OwenAmbur** [comment]
The nouns (element names) can be defined in xsd:Documentation in XML schemas (XSDs) and the schemas themselves specify the structure and relationships among the elements.  

See, for example, the data dictionary for StratML Part 2, Performance Plans & Reports, automatically generated from the schema using oXygen:  http://xml.fido.gov/stratml/references/PerformancePlanOrReportISODRAFTVersion20160216.html

One of the unrecognized implications of Executive Order 13642, Making Open and Machine Readable the New Default for Government Information, is that XSDs should be specified for all Federal records series.  http://xml.fido.gov/stratml/carmel/EOOMRDwStyle.xml & http://www.archives.gov/records-mgmt/faqs/federal.html#series
