### ISSUE TITLE
Modifications to guidance around data rights should go beyond TechFAR to the full FAR 

### ISSUE THREAD

**Issue by NoahKunin** [WhiteHouse/source-code-policy#197]
_(I’m Noah, the Infrastructure Director at [18F](https://18f.gsa.gov/), an office in the [U.S. General Services Administration](http://www.gsa.gov/) (GSA) that provides in-house digital services consulting for the federal government. I’m commenting on behalf of 18F; we’re an [open source team](https://18f.gsa.gov/2014/07/29/18f-an-open-source-team/) and happy to share our thoughts and experiences. This comment represents only the views of 18F, not necessarily those of the GSA or its Chief Information Officer.)_

While incorporation into the TechFAR will assist in the enforcement of this policy, if OMB wants to improve compliance with this policy in procurements, then relevant FAR sections should be modified, especially to cover custom software created for Government contracts, both for the first time and for any refactoring to existing code.

There are many edge cases whereby the current FAR sections are inadequate, such as Data Rights (Subpart 27.4), in light of this policy as well as protecting the taxpayer’s interests generally.

Consider: while the Government may obtain "unlimited rights" to all code created during  the performance if such code is a deliverable, which may not be the case depending on how the contract is written which is even more problematic, how does the Government know if any particular element of the code was created before the procurement started? 

As currently written, the FAR creates an opportunity for vendors to claim a particular piece of code as a “prior work” and argue that such code becomes  exempt from the "unlimited rights" provision, which also happens far too frequently in practice. 

The current FAR language is too nebulous and should be reconsidered to better ensure that when vendors include prior code, that was truly created before and _without_ taxpayer funds, they must grant the Government similar unlimited rights for the previously created work.

If vendors cannot grant such rights, or simply do not wish to do so, they must be required to expressly receive written permission from the Government to include code into the vendor's deliverables. All too often these conversations are left at the end of the effort, for contract close-out or even post close-out, leading to considerable confusion and consternation between the Government and vendors as to who has the rights to what.

**Comment by jbjonesjr** [comment]
A key piece to this policy will be refinements in wording and implementation of the FAR and TechFAR during procurement. I look forward to updated guidance and wording to make it easier for the government to retain rights (and access) to the software they have already paid for.

**Comment by danbernier** [comment]
Some relevant info & links for anyone coming into this cold (like me):
- FAR = Federal Acquisition Regulation
- [The TechFAR Handbook](https://playbook.cio.gov/techfar/)
- [The TechFAR Online](https://github.com/usds/playbook/blob/gh-pages/_includes/techfar-online.md)
