### ISSUE TITLE
Email Comment: Support for "Free Software"

### ISSUE THREAD

**Issue by OMBPublicComments** [WhiteHouse/source-code-policy#207]
[Email Comment, received on 4/15/2016 at 1:38PM ET]

I urge the federal government to recognize and include the term "free software" and the Free Software Definition (http://www.gnu.org/philosophy/free-sw.en.html), indicating that this policy is designed to protect the autonomy of government and the rights of its people.

The proposal to release 20% of custom code each year should be changed. 
Please require the releasing of all code as free.

Additionally, free documentation should be included in the policy.

The federal government needs to address its contradictory habit of requiring or recommending the use of proprietary software, including non-free JavaScript.

The government should not require use of GitHub either in order to contribute to government projects under this initiative. Please check out a better criteria here http://www.gnu.org/software/repo-criteria

Christopher Waid
ThinkPenguin, Inc-CEO

**Comment by danbernier** [comment]
As much as I appreciate the concern of using a corporate-provided system like GitHub for a government effort to encourage openness, GitHub is where the open-source party is currently at. Moving away from that creates one more obstacle to this happening. I'd rather see this project start by using GitHub, and become successful. Once that happens, we can consider moving to a freer platform.

_Originally appeared on duplicate issue #212._

**Comment by OMBPublicComments** [comment]
[Email Comment, received 4/16/2016, at 2:49AM ET]

[Comment added to this thread as the text is nearly identical to the text in the first comment at the top of the thread]

Please find here some important points for improvement on the proposed U.S. Federal Source Code Policy.

The proposal could be a big step in the right direction for the U.S., and I suggest several improvements:
• I urge the federal government to recognize and include the term "free software" and the Free Software Definition, indicating that this policy is designed to protect the autonomy of government and the rights of its people.
• The proposal is to release 20% of custom code each year: I recommend releasing all code as free.
• Additionally, free documentation should be included in the policy.
• The federal government needs to address its contradictory habit of requiring or recommending the use of proprietary software, including non-free JavaScript.
• The government should not require use of GitHub in order to contribute to government projects under this initiative -- the Free Software Foundation's code repository criteria explain important concerns in this area.

Thank you for your attention.
- Elie Calhoun

**Comment by OMBPublicComments** [comment]
[Email Comment, received 4/17/2016, at 2:47PM ET]

[Comment added to this thread as the text is nearly identical to the text in the first comment at the top of the thread]

We suggest several improvements: 
- We urge the federal government to recognize and include the term "free software" and the Free Software Definition https://www.gnu.org/philosophy/free-sw.html , indicating that this policy is designed to protect the autonomy of government and the rights of its people.
- The proposal is to release 20% of custom code each year: we recommend releasing all code as free.
- Additionally, free documentation should be included in the policy.
- The federal government needs to address its contradictory habit of requiring or recommending the use of proprietary software, including non-free JavaScript.
- The government should not require use of GitHub in order to contribute to government projects under this initiative -- our code repository criteria http://www.gnu.org/software/repo-criteria  explain important concerns in this area.

Thank you for your consideration.
Regards,
The Dimovs

**Comment by OMBPublicComments** [comment]
[Email Comment: Received on 4/17/2016 at 9:37PM ET]

[Comment added to this thread as the text is nearly identical to the text in the first comment at the top of the thread]

Dear Administrator Scott:

Firstly, thank you for accepting comments from the public regarding the US Federal Source Code Policy proposal.

I believe that government transparency policies such as this are vital to the functioning of a healthy democracy. 

Though this is a great first step, I wish to echo the suggested improvements to the initiative outlined by the Free Software Foundation and its Executive Director, John Sullivan.

These improvements, further summarized in the Foundation's 15 April blog post, urge for the federal government to:
• Recognize and include in the policy proposal the term "free software" along with the Free Software Definition.
• Release all code as free.
• Include free documentation in the policy.
• Rectify its contradictory habit of requiring or encouraging the use of proprietary software, which extends to non-free JavaScript.
• Not require the use of GitHub in order to contribute to government projects under this initiative (see the Foundation's code repository criteria for details regarding this concern).  
Thank you for your consideration.

Sincerely,
George Jones
