### ISSUE TITLE
We need to go beyond open source to open usable sources

### ISSUE THREAD

**Issue by DeenaLarsen** [WhiteHouse/source-code-policy#208]
We have a wide variety of complex programs for facilities, operations, restoration, and more. These programs need accurate data—tracking water, fish, sediment, hydropower, and so much more is vital to managing our programs, infrastructure, and resources.  And our projects are not becoming simpler—indeed,  data acquisition and analysis requirements have skyrocketed in today’s complex environment.  Yet our managers often have to find stove-pipe applications that are essentially the same as every other stovepipe--we reinvent the stovepipe each and every time. Why? Because we don't know what is out there to use for data management, visualization tools, etc. 

So, could we expand this open data policy to be a clearinghouse of:

Answers.  I go to the site and type in my question (need to know about sea level rises in LA) and I get a cross referenced search of tools, data, and software already developed for this need.

Applications. I have an open source app (like Pisces https://github.com/usbr/Pisces). I fill out a form that tells folks about it and people can then get the code, work it out, etc.

**Comment by DeenaLarsen** [comment]
Also, on a slightly related note, we need open source ways to provide metatags and QA/QC for data. And to bring all of the data and data visualization apps together. For example, we have a great GIS data visualization tool--http://usbr.maps.arcgis.com/apps/MapJournal/index.html?appid=cd222d3af91a4a078a1a8d73d168a270.  Couldn't someone else use this as a basis for accessing even more data? or couldn't we have a single GIS system across Fed, state, local, tribal, and non-governmental organizations where all data and reports for one location could be accessed?
Well, only IF everyone knows about everyone else's programs, data, and reports!

**Comment by OwenAmbur** [comment]
If the Federal Enterprise Architecture (FEA) Data Reference Model (DRM) had been implemented effectively, it would be possible to easily discover applicable data sources.  

However, short of that, it would be helpful if the goals, objectives, and stakeholders of each data source were documented in an open, standard, machine-readable format like StratML (ISO 17469-1).

**Comment by DeenaLarsen** [comment]
We also need time and resources to identify data sources. There have been times when data sets are not shared because we do not have time or funding to provide metadata or to document the sources.
