### ISSUE TITLE
Explain the expected role of communities in secure open source development of government software

### ISSUE THREAD

**Issue by brittag** [WhiteHouse/source-code-policy#214]
_(I'm Britta Gustafson, a content designer at_ [_18F_](https://18f.gsa.gov)_, an office in the_ [_U.S. General Services Administration_](http://www.gsa.gov) _that provides in-house digital services consulting for the federal government. I'm commenting on behalf of 18F; we're an_ [_open source team_](https://18f.gsa.gov/2014/07/29/18f-an-open-source-team/) _and happy to share our thoughts and experiences. This comment represents only the views of 18F, not necessarily those of the GSA or its Chief Information Officer.)_

We suggest clarifying "[Leveraging Existing Communities](https://sourcecode.cio.gov/OSS/)" (5.2.a) to explain in more detail what the policy recommends for ownership and maintenance of government-created open source code. This section is currently ambiguous since "communities" is a broad term that can be used and interpreted in multiple ways.

We also suggest including guidance in Project Open Source to help government teams understand what to expect from working with external contributors to open source projects, including how to approach building secure software in the open.

To inform this clarification and guidance, here's an explanation of how we develop open source projects with public collaboration, along with specific recommendations based on our experience.
### How we manage our open source work

At 18F, we develop almost all of our custom code as open source projects with limited government-only "ownership"/maintainership (administrative control). The only people with access to add/modify code for these projects are 18F staff and any appropriate staff from government partners we're working with (such as our federal agency clients and fellow federal staff in the White House US Digital Service). We encourage external people (such as people from other parts of government and the public) to propose contributions to our projects, but 18F staff members carefully review those suggestions before accepting them into the project (and will reject them if they don't meet our standards for security and quality). Our standards for running our open source projects are based on [this guide to FISMA-compatible usage of GitHub](https://github.com/fisma-ready/github) (which we helped write). People from the public are welcome to make their own copies ("forks") of these projects and modify/maintain them as they wish, but those copies don't automatically affect the repositories we use for our work.

We also co-maintain a few open source projects in collaboration with non-government partners, such as [Compliance Masonry](https://18f.gsa.gov/2016/04/15/compliance-masonry-buildling-a-risk-management-platform/), and we have careful standards for how we choose to do that and how we integrate that code into our work. We also reuse externally-created open source projects (after reviewing them) and customize them, and we participate in those projects by contributing back our improvements when we can ([such as this example](https://18f.gsa.gov/2015/06/03/giving-back-to-open-source/)).
### Our perspective on the role of external contributors

We encourage external contributions to our open source software — for example, we [promote "help wanted" tasks to the public](https://github.com/search?q=user%3A18f+label%3A%22help+wanted%22) and [promote our easily-reusable projects](https://18f.gsa.gov/2016/04/06/take-our-code-18f-projects-you-can-reuse/) ([including to other government workers](https://18f.gsa.gov/2016/04/13/7-18f-projects-that-state-and-local-governments-can-reuse/)). We appreciate when volunteers and people working for other groups propose contributions to our projects; this is valuable and supports our mission. However, we don't rely on external contributions for core custom development work; our staff is responsible for developing and maintaining our code as secure and functional code (and for transitioning this responsibility to our agency partners when we complete a project engagement with them).

We don't expect substantial external contributions for all projects; the amount we get varies based on the type of project and the amount of outreach we do. If we get few external contributions to a project, that's not a problem for our work. We still get important benefits from developing the project in the open, including transparency/accountability, frictionless collaboration among staff/partners, extra motivation to do the work well, and the opportunity for that work to be reused by somebody else later.

We recognize that for our open source projects, external contributors are generally doing voluntary work. For example, they may be volunteers donating skilled work for free with altruistic motivations, or to practice their technical skills to improve their job prospects. External contributors may also be paid staff for groups reusing our work that are voluntarily choosing to contribute their improvements back to our projects — this is often due to a combination of altruism and making maintenance easier for themselves (minimizing divergence of codebases can help them use 18F's future improvements to that project).

Specifically regarding security: as government staff, we consider ourselves responsible for developing and maintaining software that is adequately secure without depending on review from external volunteers, whether our software systems are closed source or open source. We develop our work as open source software partly because we get the great potential benefit of external volunteer review, but it wouldn't be appropriate to depend on active or continuous volunteer review for the security of our work; our teams must include paid staff with security skill.
### In the policy: clarify how to leverage existing communities

"[Leveraging Existing Communities](https://sourcecode.cio.gov/OSS/)" (5.2.a) is somewhat ambiguous about whether 18F's standard practice is acceptable, primarily since "community" is a broad term that can be interpreted in multiple ways. This item should be revised to be more specific, including defining "communities". It's unclear whether it's adequate to make a reasonable effort to share government-created custom open source software with the public so that a broader community of practice can adapt it and suggest improvements, or whether the policy expects that government staff should try to get government-created custom code incorporated into projects that external people maintain.

As an example: we use an external open source project to run our 18F blog ([Jekyll](https://jekyllrb.com/)) and develop and maintain a few custom open source plugins to help us run the blog, such as [jekyll_frontmatter_tests](https://github.com/18F/jekyll_frontmatter_tests). It's a common practice among Jekyll users to build plugins and share them with the public as OSS. Is it adequate that 18F releases our plugin as OSS? We also uploaded it to a package management system (RubyGems) commonly used by Jekyll users, to support easy findability and reuse by the public. Do we also need to propose to the Jekyll project that they consider listing our plugin on the [Jekyll Plugins page](https://jekyllrb.com/docs/plugins/)? To interpret the recommendation even more broadly: do we need to try to find external people who use Jekyll to help us maintain this small tool? Or is it ok for us to just keep being owners and maintainers of the plugin as part of our ordinary work, which we would also have to maintain if we had a closed-source system for our blog?

A suggestion for revising this section:

> Leveraging Existing Communities – Whenever possible, teams releasing custom code to the public as OSS should appropriately engage and coordinate with existing communities of practice relevant to the project. For example, there are already existing communities of practice (including communication channels, open standards, and open source projects) for electronic health records and geospatial software,[37] so government agencies working on related OSS projects should look for opportunities to participate in them, such as by partnering or interoperating with related projects.
### In Project Open Source: include guidance for working with external contributors

To help teams shift to OSS development, Project Open Source could explain examples of appropriate permissions structures for government teams developing OSS projects, such as limiting administrative rights to a core team of government staff and allowing proposed contributions from the public that the staff reviews before acceptance/rejection.

As suggestions for best practices that Project Open Source can recommend for user engagement, we'd suggest covering topics including:
- "Communities" are made of individuals; rather than thinking of communities in broad terms, it can be very helpful to think in specific terms about the needs and goals of potential external contributors to projects.
- Recruiting external contributions usually requires some skill and effort, rather than happening automatically when you release OSS.
- Teams need to be appropriately staffed for projects rather than relying on external contributors for core work.
- It's important to graciously respect that external contributors are giving voluntary work.
- It's unusual but possible for external contributors to be rude or otherwise behave inappropriately, and there are best practices for establishing processes and policies to handle this appropriately. Your agency likely already has a policy that you can adapt for your OSS work. For example, GSA has a [Policy Statement on Harassment](http://www.gsa.gov/portal/directive/d0/content/512516), and 18F builds on that policy for our [code of conduct](https://github.com/18F/code-of-conduct/blob/master/code-of-conduct.md) that applies to all of our work.

**Comment by danbernier** [comment]
> It's a common practice among Jekyll users to build plugins and share them with the public as OSS. Is it adequate that 18F releases our plugin as OSS? We also uploaded it to a package management system (RubyGems) commonly used by Jekyll users, to support easy findability and reuse by the public. Do we also need to propose to the Jekyll project that they consider listing our plugin on the Jekyll Plugins page? To interpret the recommendation even more broadly: do we need to try to find external people who use Jekyll to help us maintain this small tool? Or is it ok for us to just keep being owners and maintainers of the plugin as part of our ordinary work, which we would also have to maintain if we had a closed-source system for our blog?

I think this is an excellent point. RubyGems and Jekyll plugins are existing communities of developers, and policy should be to work with those communities.

This issue generally reflects a thorough working understanding of open-source development. :+1: Nice job, @brittag.
