### ISSUE TITLE
"Posted publicly here" link not very public

### ISSUE THREAD

**Issue by melbamorph** [WhiteHouse/source-code-policy#22]
I obviously have a github account, but for people who do not yet have one, when they click on the part of the introduction page that says: 

> Please note that all comments received will be posted publicly here.

The link "here" points to: https://github.com/whitehouse/source-code-policy/issues/new and redirects the viewer to GitHub's login page before they can proceed. Any possibility of this being changed so they can view the public comments without signing into GitHub?

**Comment by gbinal** [comment]
Great point.  

This seems to have been addressed with [this commit](https://github.com/WhiteHouse/source-code-policy/commit/ca14bb5856b4bd7eea20274d258d7977bf3206f1) and is [updated in production](https://sourcecode.cio.gov/).  It looks like we can close this issue.
