### ISSUE TITLE
[Request for discussion] How to Assist Agencies In Leveraging Communities: reincarnate "Civic Commons" style App Catalog

### ISSUE THREAD

**Issue by andrewhoppin** [WhiteHouse/source-code-policy#238]
(I'm Andrew, currently leading an open source enterprise software line of business, and formerly the NY Senate CIO, where we launched the first ever government Github repository in 2009; opinions are my own.  I worked as a vendor on the Civic Commons project in 2011 and 2012).

Assisting Agencies in Leveraging Existing Communities (section 5.2):

There is a big difference between a Github project that someone created at a hackathon last year, and a thriving sustainable open source project; the latter is necessary in order to fully realize maximum possible benefit of open source adoption and contribution in re: total cost of ownership, security, and innovation for Agency IT projects.  Therefore it will be critical to assist Agency technology buyers in identifying successful, sustainable existing open source communities / projects that are promising candidates to leverage and extend, so that their new "custom" code need not be "from-scratch" unsupported code.     

Available metrics from code repositories like Github, and analytical tools like [OpenHub](https://www.openhub.net/) can assist, but the social context of who is using what where, and how well it's going, is also critical.  While there are a growing array of thriving open source enterprise companies working with governments, government buyers are still often left to choose between a proprietary product that has the support of comprehensive sales collateral and case studies available from a professional software sales organization, or an open source project with zero sales or marketing support.   

In order to put all relevant software on a more level playing field, a searchable government software usage metadata catalog should be created to leverage the new Agency software inventories that will emerge, at an expanded apps.gov, or equivalent, much as data.gov puts a friendly UI on Agency's data.json feeds.

These suggestions recall the brief Civic Commons project supported by the Knight Foundation, Open Plans, and Code for America, which briefly in 2011-2012 catalogued metadata of 100s of of software apps in use by governments, and 10,000s of unique deployments of these apps.  The concept, later also explored by the World Bank and Code for Europe, was shut down for lack of sustaining funding, but there is extensive background available on the rationale and model:

http://archive.civiccommons.org/
https://www.drupal.org/project/opencivic
https://joinup.ec.europa.eu/

Many of the lessons learned, and potentially even some of the open source code, developed for Civic Commons could be applied to a new Apps.gov or equivalent that leverages an expanded data.json feed of software in use at all Agencies, and potentially also be enriched by harvesting analogous metadata from State and local governments as well.

This post relates significantly to #116 and #214 as well.

**Comment by philipashlock** [comment]
I was recently speaking to Jean Paulo Gil Barroca from the World Bank and he mentioned that he often referred to catalogs like Civic Commons as a reference for other countries and was dismayed to see them go offline. So it's also worth considering the influence of these efforts on other countries.
