### ISSUE TITLE
Email Comment: Code Inventories and Discovery

### ISSUE THREAD

**Issue by OMBPublicComments** [WhiteHouse/source-code-policy#24]
Reference:  Code Inventories and Discovery – Beginning at Line Number 342

The effective reusability of “anything” parallels what has been learned in the library sciences.  Three things are required for effective reuse:  (1) a classification scheme for storage and retrieval of content (a Dewey decimal-like structure), (2) artifacts (code) actually designed for reuse, with reuse as an explicit design intent, and (3) a librarian to manage the reuse library.

We suggest that a classification system is vital, and begins with the six interrogatives used to describe “anything” – What, How, Where, Who, When, and Why.

Providing examples of these six interrogatives in the context of Code, the classifications would represent indexing, at the highest level by:

Why – Strategies/Goals
           How – Processes/Activities
           What – Materials/Things
           Who – Roles/Responsibilities
           Where – Locations/Geography
           When – Events/Triggers

Of course, as is in the Dewey Decimal System, refinement from this initial ontological classification is required.

We suggest that this effort be done prior to any Code Inventory, or at least, parallel to the development of the Code Inventory.  This “salad bar” approach to system development is the highest (third level) of enterprise system maturity:  Level 1 – Make to Order, Level 2 – Provide from Stock (COTS packages), and Level 3 – Assemble to Order (minimal/or no handcrafting/writing of code).  This approach requires a true reuse code inventory ontology that represents the Level 3 desired maturity.

Past efforts in this domain suggest, that no matter how good the code itself is, the classification of the code is key to not having a disorganized and potentially bloated inventory, and being able to locate potential reuse candidates.

An incentive system needs to be designed and implemented that rewards reuse of code.  This is not only by “mandate” but by actually providing “rewards/compensation” for actually not writing new code.  Today’s programming / agile programming approaches, and the community involved with these approaches, are in conflict with code reuse.  As an incentive example, a person/vendor would be paid “X” for reusing code, which in some cases, would be more compensation than writing new code.  The cost of new code development and code vetting is extreme in comparison to reuse.  We suggest that the incentive system design and implementation also proceeds or parallels the Code Inventory development.

Respectfully:
Samuel (Sam) B Holcman
Pinnacle Business Group, Inc.

**Comment by mikeBeviBevi** [comment]
I really like your recommendation for the inventory schema.  Could you please provide a reference for the definition of enterprise system maturity levels you refer to?

I would disagree with your evaluation that today's programming / agile programming and their communities are in conflict with the reuse of code.  I believe that this has more to do with the actual design and implementation and less to do with the development process life cycle. That being said, I would also argue that these methodologies are used in the open source communities that are creating the reusable code that is the force driving the need for this policy.

I think the incentive models that your are suggesting are not in the spirit of general open source projects nor this federal open source policy.

I do not think that an incentive program has anything to do with the code inventory development.  This suggests that one should be paid for any contributions to an open source project.  To me, the fact that comment is being accepted in this forum suggests that the development of this policy is closer to a open source project that it is describing.
