### ISSUE TITLE
THE PUBLIC COMMENT PERIOD IS NOW CLOSED

### ISSUE THREAD

**Issue by OMBPublicComments** [WhiteHouse/source-code-policy#249]
The public comment period has ended. Thank you for your comments. OMB will analyze all feedback submitted during the public comment period and revise the policy as necessary. 

All issues submitted during the public comment period will be closed to mark them as officially recorded with the exception of a few threads started by 18F under the headings "[Request for discussion]". We welcome you to open new issues to start or continue any other further discussions regarding this policy, but they will not be counted as official public comments.

**Comment by jackiekazil** [comment]
Thank you for taking this approach to create a dialog online and being transparent about the process! <3 <3 <3

**Comment by suchow** [comment]
How will the OMB handle pull requests?

**Comment by chasingamy** [comment]
@suchow Pull Requests for non-technical issues (meaning issues that aren't about the GitHub page itself, but rather are changes to the policy document) will be treated in much the same way as an Issue that asks for specific changes to the policy document. We will review all changes proposed in pull requests that were submitted before the public comment deadline and revise the policy as necessary.
