### ISSUE TITLE
This is awesome

### ISSUE THREAD

**Issue by mlipman** [WhiteHouse/source-code-policy#25]
And not just because my github profile will say I've contributed to the WhiteHouse's repo. 💯💯💯💯

**Comment by esplinr** [comment]
As a U.S. taxpayer, I'm excited to see more of my tax dollars going toward development that benefits the entire industry, instead of being stuck in private repositories where it can't be reused.

**Comment by technologiclee** [comment]
We should have a discussion space like this for all policy.
