### ISSUE TITLE
Note to clarify exception publication on code.gov

### ISSUE THREAD

**Issue by konklone** [WhiteHouse/source-code-policy#251]
I know the policy is final, but something to flag for clarification on code.gov -

On the [Exceptions page](https://sourcecode.cio.gov/Exceptions/):

> For excepted software, agencies must provide OMB a brief narrative justification for each exception, with redactions as appropriate.

Presumably agencies don't need to redact the information for OMB, but for the public -- but the sentence doesn't explicitly say that OMB will (or the agency should) make the justification public. If OMB wants the justification to be public, it should be explicit about this somewhere.

**Comment by mattbailey0** [comment]
Captured on https://github.com/presidential-innovation-fellows/code-gov-web/issues/32
