### ISSUE TITLE
Appendix 404

### ISSUE THREAD

**Issue by rossdakin** [WhiteHouse/source-code-policy#253]
https://sourcecode.cio.gov/AppendixA/

@mattbailey0 identifies this as a case-sensitivity issue.

h/t @JustinHerman

**Comment by rossdakin** [comment]
Fixed by 935828b2073fd02b5b63925abd1222bfdbd515b9

**Comment by mattbailey0** [comment]
Thanks @JustinHerman!

**Comment by JustinHerman** [comment]
Glad to help -- looking great, can't wait to deep dive in.
