### ISSUE TITLE
[Request for discussion] open source tool for requirements tracking

### ISSUE THREAD

**Issue by vitiral** [WhiteHouse/source-code-policy#254]
What requirements tracking tool does the goverment prefer?

I have created an open source requirements tracking tool that is designed to be easy for developers to work with. Check it out here:
https://github.com/vitiral/rst

**Comment by vitiral** [comment]
Benefits:
- easily write requirements and link them to eachother
- easily link requirements to source code
- track progress of requrements throughout entire project

**Comment by david-a-wheeler** [comment]
Please don't create new issues.  This is the issue tracker for the US Federal Government source code policy.  This has now been released, so adding issue trackers here is irrelevant.

**Comment by david-a-wheeler** [comment]
It may not be useful to create new issues  here.  The source code policy has been released.
