### ISSUE TITLE
20% code release

### ISSUE THREAD

**Issue by neilmartis** [WhiteHouse/source-code-policy#257]
I can see this happening across agencies and Departments and feel very proud to contribute to source code as it builds trust,collaboration,team work,knowledge sharing across industry and its a good policy to have.It good to start with a small percentage and once we are able to gauge the impact we can always the increase the code release percentage.Win-Win for everyone.I am happy as this a huge step in the right direction not only for the United States but also as an example for the rest of the world to follow.

**Comment by trevor-vaughan** [comment]
I would like to say that, before you say it can't be done, this should help, https://github.com/NationalSecurityAgency.

The [NSA Technology Transfer Program](https://www.nsa.gov/what-we-do/research/technology-transfer/) is doing some great work moving this forward.

**Comment by neilmartis** [comment]
@trevor-vaughan I am already aware about it!Thank you once again!

**Comment by mattbailey0** [comment]
Closing this given the more active conversation on #259
