### ISSUE TITLE
Policy PDF is missing

### ISSUE THREAD

**Issue by jfredrickson5** [WhiteHouse/source-code-policy#266]
The "View PDF of Policy" link at the top right of the policy website is not working.

**Comment by JGerding** [comment]
It is still available on the Obama White House archive, if you need to access it in the meantime: https://obamawhitehouse.archives.gov/sites/default/files/omb/memoranda/2016/m_16_21.pdf

**Comment by AlvandSalehi** [comment]
This has been resolved. Thanks for the flag!
