### ISSUE TITLE
Plugins and Extensions to closed-source COTS and Middleware

### ISSUE THREAD

**Issue by bushidocodes** [WhiteHouse/source-code-policy#31]
Please clarify the impact of the government requesting functional enhancements to closed-source COTS and Middleware. Given that agencies typically don't have sufficient software engineering talent to customize COTS, they work with systems integrators to build customize enhancements for these products. Systems integrators like to retain ownership (souce code of plugins and exclusive admin control of platforms) of these closed-source customizations to have leverage to force sole-source contracts for ongoing maintenance. More recently, the integrator will call this a SaaS offering (targeting a single customer). According to the spirit of this document, I would expect that the government agency should take delivery of the source-code for all plugins and custom enhancements and release the codebase as open-source as this policy stipulates. To do this, the government need to properly license managed COTS and middleware products to retain admin rights and have access to APIs and the relevant plugin architecture. Please add content to the document targeting anti-competitive systems integrator practices to ensure clean acquisition of closed source platforms and the open-sourcing of plugins to those platforms.

**Comment by stevenhaddox** [comment]
@spmcbride1201: I've actually worked on government contracts and created COTS enhancements / functionality tweaks in the past. I don't see how licensing is relevant to this in the way that you've presented it. On contracts where a COTS tool is being modified with the help of the COTS company I would assume licensing would be handled on a contract by contract basis; however, in situations where the government is creating a custom feature, add-on, or modification to COTS code, and the code doesn't modify the COTS tool itself (e.g., it is created as an external library such as a ruby gem or node package), then that code has been fully paid for by the tax payers and should be able to be published as OSS.

Now, utilizing that OSS library would obviously require that you'll need a licensed copy of the COTS software that it has been designed to interact with or modify before it would do you any good.

Do you feel that this is changes your thoughts at all? Essentially I got the impression that the government should be open sourcing any code it creates that isn't included in the exceptions clause. I would assume that the exceptions clause would probably include licensing that prevents it from sharing in-line changes to licensed software (but maybe that needs to be a new issue).

**Comment by bushidocodes** [comment]
Thanks for your quick response!

> in situations where the government is creating a custom feature, add-on, or modification to COTS code, and the code doesn't modify the COTS tool itself (e.g., it is created as an external library such as a ruby gem or node package), then that code has been fully paid for by the tax payers and should be able to be published as OSS.

This quote gets to the core of how I think this should operate. This definitely has a huge impact for some of the cloud middleware that the FAA is working to standup.

Apologies for rambling in my earlier message, but I was thinking less about software vendors like Microsoft and more about systems integrators. Think [these guys](https://fcw.com/Articles/2012/09/28/fedlist-systems-integrators.aspx).

For example, consider the following scenario:
1. Agency A releases an RFP for a continuous monitoring security solution complaint with Federal Regulation Z.
2. McBride Systems Integrator (SDVOSB) bids for the RFP with EMC as a sub-contractor. McBride Systems Integrator's proposed solution is a custom implementation of RSA Archer that uses the Archer web services APIs behind the scenes, performs some significant work on top of those APIs, and presents a custom web portal to Agency A. The solution is marketed as a custom SaaS implementation.
3. Agency A selects the McBride Systems Integrator solution for closely complying with the requirements. Because they interact with the custom web portal showing Agency A's logo, they don't know that the solution is built upon RSA Archer or where the delineation is between COTS software licensed from EMC and custom code written by the systems integrator. 
4. At a government security conference, McBride Systems Integrator begins advertising general availability of a new SaaS offering targeting compliance with Regulation Z, listing Agency A as a marquee customer 

Given that Agency A effectively bankrolled the development of custom code on top of a well defined interface to a COTS product, wouldn't this policy require McBride Systems Integrator to hand over all IP rights to the custom code developed on top of RSA Archer? 

Sorry for the silly example! Brain is pretty fried, and I occasionally daydream about revolving-door my way into an SDVOSB after a long day. :)

**Comment by johnmod3** [comment]
this seems sort of edge-casey. Yes there will be cases where the Gov can't (or doesn't control) the underlying IP, but this policy is a start that will generate and reward increasing Open behavior
