### ISSUE TITLE
Where is this policy???  Found it, but...

### ISSUE THREAD

**Issue by mcswell** [WhiteHouse/source-code-policy#34]
It was very hard to find the text of this policy.  There is no link afaict on the blog page that announced it (https://www.whitehouse.gov/blog/2016/03/09/leveraging-american-ingenuity-through-reusable-and-open-source-software). There is a link on the discussion page (https://sourcecode.cio.gov/), but it's labeled "View PDF", which sounds like it's just another way to view the discussion page--but it is in fact the actual policy.  I think you should put up links on both pages that are clearly labeled "View policy (PDF)" or some such.

**Comment by nyeates** [comment]
I will second this. The blog does link to https://sourcecode.cio.gov/ at the VERY end, in a single word that says "here". Heh. Not too obvious. It should be up front and clear and not say anything about a PDF (the format is relatively irrelevant).

Example:
[Federal Source Code Policy](https://sourcecode.cio.gov/SourceCodePolicy.pdf) – Achieving Efficiency, Transparency, and Innovation through Reusable and Open Source Software - [access policy source here](https://github.com/WhiteHouse/source-code-policy/tree/gh-pages/pages)

**Comment by AlvandSalehi** [comment]
Thanks for the feedback @mcswell and @nyeates !  We just updated "View PDF" to "View PDF of Policy."  

Hope that helps!
