### ISSUE TITLE
Confusion about scope -- questions about who would have to make what open-source

### ISSUE THREAD

**Issue by JacksonBailey** [WhiteHouse/source-code-policy#35]
Let's say that a hypothetical big government agency (BGA) needs some hypothetical software that bakes digital bagels.

They determine that there is no current in-house or open-source solution to bake digital bagels, so they contract some hypothetical big software company (BSC) to make their digital bagel baking software.

**Does this mean that BSC's digital baking software would have to be open-source, or... what?** Or am I completely misunderstanding, and only code that BGA makes needs to be made open-source?

---

Also, let's say that BSC already has some existing, but closed-source, digital oven software. They only need to add the digital bagel functionality to the digital over software. **What does this imply?** Does all of the digital oven software have to be made open-source or only the "digital bagel module"?

**Comment by johnmod3** [comment]
New code would need to be made Open

**Comment by francisrupert** [comment]
Bottom line: software developed on **BGA's dollar** shall be OSS. Thus...
- Under your latter scenario...
  - BSC's **digital oven software** (developed with **BSC's** dollars) remains **Closed**.
  - BSC's **digital bagel module** (developed with **BGA's** dollars) shall be **Open**.
- If BSC made the **entire** shebang for BGA, it's all Open.
