### ISSUE TITLE
Incentive or requirement for actual reuse of existing code

### ISSUE THREAD

**Issue by chipmonkey** [WhiteHouse/source-code-policy#36]
One of the key cost-savings components of Open Source software is the ability to re-use code; the policy emphasizes this, but it incentivizes only the creation and publication of code that can be reused by other people or other portions of the government.

It does not, to my reading, actually push for any savings by actually consuming that code again, and I'd like to see some discussion of how that could be improved.  Section 5.2 a) touches on it, and the procurement policy in Appendix B indicates OSS should be procured preferentially in Step 1, but at Step 3 it seems like an all-or-nothing affair, while in reality we want to espouse significant attempts to reuse OSS code and libraries.  In any case these brief mentions are not strongly represented in the rest of the document.

I'd like to add an "Objective" that indicates some measure of _actual reuse_, and replace "reuse" in objective 2 with "publication" or something.  This is to clarify that the publication and consumption (reuse) of OSS code are two related but separate goals.  Code is not re-used if it's simply available.

We could consider another goal (10%? 20%?) to have the code in a new government funded project make use of existing OSS code (government or not).  This is a pain to measure, but the point is there's little benefit to having a library of open source code if no one uses it.  The objectives should indicate this.

(I may take a stab at composing such an objective later, depending on feedback here).

At minimum, relatedly, OMB should explicitly add a metric to track OSS code consumption, rather than just publication.  Again, this is onerous, but I think it's essential for realizing cost savings.

**Comment by crdunwel** [comment]
@chipmonkey - this exact thought came to mind when reading section five so I'm glad I'm not alone in thinking this is an issue. The wording of this policy seems to focus primarily on publication and discoverability of code, but as you've identified, doesn't quite adequately lay out policy to incentivize code reusability. IMO, the nightmare scenario that may result (especially with this arbitrary 20% newly developed-code goal) is that the agencies pay for code with no real utility that is virtually un-reusable for the purpose of checking off a box to fulfill a mandated policy requirement. Not exactly the best use of tax payer money.

Instead, the policy could be written such that agencies are incentivized (as you suggest) to create and/or utilize reusable code and maintain/report metrics of who reuses and contributes to that code. Further, if leveraging the benefits of OSS optimally then less code should ultimately be written and more code should be adopted and configured for specific use cases by other agencies. Thus, an agency may fail the 20% requirement if they're so good at reusing code that they write very little of their own (but contribute to existing project, perhaps originally created to solve a problem at another agency).

Tangentially related questions, where applicable -

1) Is there any language in the policy requiring code to be released in versioned repositories? Git is preferable for obvious reasons but plenty of popular versioning software out there.
2) Are there any requirements for continuous integration or any form of an automated test suite whatsoever? Reusability w/ modification suffers tremendously without a test suite.

Section 5.2 identifies some good principles for leveraging open source, but I believe the section on documentation is far too minimal. While some may disagree, IMO source code is virtually useless without robust documentation. Not everybody is a ninja and sees all code as self-documenting. At the very very least, there should be a requirement for a contribution guide that includes how to set up a working development environment. If other can not easily set up the project then it's there's a significantly higher barrier to entry for allowing others to contribute (likewise if the code isn't versioned on a familiar platform and tests can't be run to insure no bugs arise from contributions).

**Comment by cherrypj** [comment]
I'm in agreement here. We use open source software, but it's heavily customized to fit our needs (is it "virtually un-reusable"? Maybe!). 

We're happy to open source it, and get credit for that, but while we have lots of documentation (primarily for the end-user, not the developer), we don't have the time to support another Agency trying to use (and modify) the code for their needs. Nor can we develop documentation for developers. We would be hard-pressed to help another Agency re-use our code.

**Comment by marteki** [comment]
> Nor can we develop documentation for developers.

Why not?

What happens when new developers join your projects now? How do they learn how to use or modify the code?

**Comment by crdunwel** [comment]
@cherrypj `"...heavily customized to fit our needs..."`,  `"...we don't have the time..."`. I think these words really characterize the nature of the problem (IMO) with how the government is thinking about and approaching open source (and in no way any fault to you). If somebody wants to deliver a working solution as quickly as possible to solve a specific problem then corners are often necessarily cut to see it happen on time and budget. It's often much harder and time consuming to produce modular and abstract solutions with the intent that others may easily use or integrate into their own projects in the future. It's also typically relatively thankless time spent if one's boss doesn't understand tech and only understands when a website or application works as a final product to an end user.

My post above seeks to highlight that the end user of any project should also be considered other developers to maximize efficient use of open source. The core issue, IMO, is that the people handling the procurement of the code aren't thinking about it from the perspective of sustainability and reusability in a larger ecosystem (and really they have no incentive to so long as they receive a final product on time and budget). I believe this needs to change if the government wants to benefit the most from open source.

@marteki I'm also curious how they handle onboarding. Do they rely entirely on current staff? Quote time - _The palest ink is better than the best memory_\- Chinese Proverb

**Comment by chipmonkey** [comment]
I think @crdunwel responded correctly to @cherrypj regarding the trade off between cutting corners and establishing a solid reusable and maintainable code base.

Ultimately the reusability of code is what drives down costs.  I've seen too many projects re-invent the wheel over and over.  Even relying on a common set of open UI components or libraries for math, encryption, hashing, database access, color schemes... there's so much that can be reused.

I've just published a pull request that takes a stab at dealing with this.  I'd appreciate any feedback.  For @cherrypj, I took an approach which included an option to certify that no code was available for reuse... that would allow a certain "out" if available code was of low enough quality so as to require more time to integrate than to rebuild from scratch (if you want to recommend edits, this could probably be a more clear intent, if it helps your concerns).

**Comment by cherrypj** [comment]
It's not so much that our code is of poor quality--I would bet a Coke that it's good stuff because we definitely haven't cut corners. Our application is built on Drupal, so we don't have developer code because they can (and should!) go to d.o. for that. Our documentation, which is very extensive (so much so it's very hard to find relevant information sometimes), is targeted at the end user. We have some custom code, and it's all written according to Drupal best practices. Should we provide documentation? I don't know.

Helping another Agency isn't so much an lack of documentation issue, but a lack of resources issues.

I definitely appreciate that Chinese proverb about the palest ink!
