### ISSUE TITLE
Contribution compact

### ISSUE THREAD

**Issue by jessebeach** [WhiteHouse/source-code-policy#37]
Similar to [Rousseau's Social Contract](https://en.wikipedia.org/wiki/The_Social_Contract), it's good to consider the establishment of behavioral norms for civic open source contribution. We shouldn't want to simply write code; we should also want to help each other understand the problems we face around this country and empathize with different solutions. Without forethought and positive standards for behavior, open source communities are prone to devolve into toxic interactions and gamesmanship. At its best, an open source community fosters the development of its members more than the development of code. 

So, here are four pithy statements I came up with, based on years of experience working primarily in the Drupal Open Source world. Drupalists maintain an OSS space of thousands of contributors that persists for over a decade. The community actively works to foster top talent and new talent; diversity and idiosyncrasy.
1. Encourage those who know less
2. Learn from those who know more
3. Be curious and courteous
4. Take pride in what we build together

Workshopping of the above statements is, of course, encouraged. If we could get it down to 3 statements, that would awesome. Most important is to express that everyone who contributes is at times a mentor and at other times a mentee. We all learn and teach and should acknowledge that a lack of knowledge is an opportunity to grow.

**Comment by mikeBeviBevi** [comment]
@jessebeach This is a great foundation to build a community upon.
