### ISSUE TITLE
Code Inventories and Discovery

### ISSUE THREAD

**Issue by dsmorgan77** [WhiteHouse/source-code-policy#40]
This section of the draft policy appears to require a new inventory. Recommend avoiding a wholly new inventory.

FAR Subpart 27.4 defines "Data" as follows: “Data” means recorded information, regardless of form or the media on which it may be recorded. The term includes technical data and computer software. The term does not include information incidental to contract administration, such as financial, administrative, cost or pricing, or management information.

Recommend adopting this definition of data and extending the coverage of OMB Memorandum M-13-13 to include code. 

Recommend leveraging the existing project open data metadata schema and requiring code repositories to be listed in the Enterprise Data Inventory. 

Recommend updating and extending the project open data metadata schema to facilitate the production of relevant metadata for a code repository.

**Comment by johnmod3** [comment]
do you have links to the "Enterprise Data Inventory." and how is it used now?

**Comment by mikeBeviBevi** [comment]
In case anyone was looking:
https://project-open-data.cio.gov/v1.1/schema/

**Comment by cherrypj** [comment]
It's not requiring a new inventory. All Agencies should already have an inventory of its information resources. It's that existing inventory that should be updated to include whether or not the code is custom. 

What **does** seem to be new is that this list of information resources must be public.

**Comment by johnmod3** [comment]
I'd say agencies know what COTS product they have licensed, they don't have a handle on taxpayer funded source code

**Comment by dsmorgan77** [comment]
@cherrypj I'll readily grant that agencies are required to have inventories of their information resources, but I think you might be surprised at what we don't know. and @johnmod3 i'll let GAO tell you how well agencies know their inventories of what you refer to as COTS products http://www.gao.gov/products/GAO-14-413

**Comment by mikeBeviBevi** [comment]
@johnmod3 individual divisions know what COTS products.  That information is not always readily available across multiple groups / branches within the same agency let alone the whole government.

**Comment by johnmod3** [comment]
@mikeBeviBevi I was being kind, some of the higher priced products (ala databases) I've seen controlled or enterprise license, but yes sadly most Agencies don't have  handle
