### ISSUE TITLE
Email Comment: Pilot Program and Exceptions

### ISSUE THREAD

**Issue by OMBPublicComments** [WhiteHouse/source-code-policy#42]
Reference: Pilot Program, Exceptions to Government-wide Reuse or to Publication

STRIKE LINES: 229-233, 235-243, 391-400, 414-416

ADD NEW SECTION TO PILOT
All Custom Code and GOTS development will contain the following provisions in all Custom Code development contracts and GOTS programs starting the effective date of the memorandum:

This software application / source code is licensed as GOTS to the Department/Agency as the sole and exclusive agent of the U.S. Government and must not be released to the public or other non-U.S. Government entities.  The government has unlimited and unrestricted government-purpose rights to the software in perpetuity; subject to the obsolescence clause below.  The Department/Agency at their discretion, may choose to share or redistribute the software application / source code to other branches of the U.S. Government at no cost to the receiving parties; and subject to the government employee and contractor clause below.    Under this license, the government has the right to alter, update, or change the software.  The Department / Agency may also utilize or authorize the modification of the software application / source code to develop alternative and derived applications for any alternative purpose; or alternatively designate in writing and post publicly any government entity for this purpose.  Parties utilizing this application/source code may not resell or re-license the source code to non-U.S. Government entities or back to the U.S. Government.

Government Employee and Contractor Clause.  Employees and contractors of the government are only permitted to modify or derive alternative applications from the source code for the sole and exclusive use of the U.S. Government.  Employees and contractors of the government who may modify or derive alternative applications from the software application / source code are not permitted to make intellectual property claims upon, or make profit from, the modified or derived source code or applications.  

Open Source Clause.  The Department/Agency may, at its discretion, determine that some or all of the application / source code is suitable for OSS release for use outside of the U.S. Government after an Agency security review and redaction of Inherently Governmental Functions that could pose a risk to the American Public or U.S. Government.  

Obsolescence Clause.  The Department/Agency CIO must be kept apprised of the re-development, maintenance, and derived applications of this software application / source code and any derived applications.  If the Department/Agency fails to utilize and maintain the software application / source code and any derived applications for a period of one year, this license is voided and the software may be petitioned for OSS release after an Agency security review and redaction of Inherently Governmental Functions that could pose a risk to the American Public or U.S. Government.

RATIONALE / DISCUSSION
Footnote 8.  Although Microsoft publishes the .NET framework and Apple provides Swift, neither publish their application source code.  An important distinction.

Software Security.  Many private companies (especially security companies) do not publish their source code is because it allows attackers to (a) construct highly targeted attacks against the software, or (b) build-in malware directly into the source code, compile, then replace key software components as 'dopplegangers' of the original.  How will this be prevented?

OSS and Inherently Governmental Functions.  This definition is insufficient.  It basically tries to leave limited discretion with the CIO, but forces them to release 20% of custom code per year under the assumption they know which custom code is safe for release.  It is clear that OSS is appropriate for functions common between the Government and Civilian sectors.  However, when Inherently Governmental Functions, non-FOIA'able, law enforcement, or security functions that are non-NSS are involved, there is risk that the Government can compromise law enforcement investigations, increase the possibility of fraud or crimes, or compromise security tools not technically NSS.  Examples: citizenship anti-fraud rules that are coded into software, identification of special codes used to flag law enforcement actions, APT threat indicator scripts, mafia having a copy of all FBI system code, terrorist with access to air traffic control software, etc.  How will this be prevented?  I can understand why OSS rules could be established to help facilitate appropriate OSS communities, but why _must_ it be 20% each year?

Altruistic Motivation.  Although Educational Institutions may wish to contribute to OSS; it is unclear whether contractors and vendors will really wish to contribute to Government Open Source improvements.  Another possibility is that the contractors or vendors will take the code, improve upon it, then sell it back as COTS to the Government.  However, if the source code involves inherently governmental functions; then information regarding those functions could be inadvertently leaked (such as law enforcement or anti-fraud / criminal activity processes, which is not a desirable outcome).

Legal Costs.  Once source code is released, it is difficult to determine if any of it has been re-utilized in other commercially available programs, such as those developed by foreign software companies.  In the event of legal action, does the Government possess the Intellectual Property and Code Vetting resources to protect its interests against commercial companies (both domestic and internationally) abusing the licensing agreement?

Fuel Innovation.  GOTS Development.  Since corporations will primarily benefit (not really the public), what motivation do Government software developers have if their custom code is given to commercial corporations to sell back to the Government for large amounts of money?  Sends the message that if you're a good code developer, you should (a) not enter or (b) leave Government service since there is nothing 'special' that they do.

Overall Cost Savings.  Although the U.S. once enjoyed a relative monopoly of software development, the growing trend is the outsourcing of software code development overseas.  "Globally, only 10 percent of MNCs outsourced IT work offshore in 2002, but that figure had risen to 70 percent by 2008, according to Oppenheimer Equity Research. Gartner Inc. estimates that by 2012, the worldwide IT services market, which is the largest segment within the outsourcing industry as a whole, will top $1 trillion."  China Business Review, China’s Emerging Role in Global Outsourcing, Nov 1, 2009.  EXAMPLE SCENARIO: Release of U.S. taxpayer-funded code development will, over time, provide foreign access to U.S. GOTS source code but without reciprocation; placing U.S. government-funded software contractors at a distinct disadvantage unless they claim proprietary software rights over the developed custom code.  Once that is done, then the software development silo is reborn (but this time in a private company that could go bankrupt or be sold to a foreign entity).  The now proprietary code could not be transferred to a new company in the case of a contract change; so the new company would be forced to develop their own system or alternatively purchase the rights from the exiting contractor.  To avoid bankruptcy, the exiting contractor could now charge what they wish for the now proprietary code (the exact spiraling cost scenario that this policy presumably claims to avoid).  Eventually, this will have the adverse effect of either (a) U.S. code developers not wishing to produce code for the U.S. Government knowing that their intellectual property could be poached by overseas competitors, or (b) ensure that only certain companies maintain proprietary code for which they could charge any amount of money they wish.

Sincerely,

Keith Hall

**Comment by johnmod3** [comment]
this proposes to perpetuate the current state of play and lacks a clear understanding about how open source communities work. 
- Software Security. Many private companies (especially security companies) do not publish their source code is because it allows attackers to (a) construct highly targeted attacks against the software, or (b) build-in malware directly into the source code, compile, then replace key software components as 'dopplegangers' of the original. How will this be prevented?
  Security by hiding source code has been shown repeatedly not to work and in fact leaves source code more vulnerable not less.
