### ISSUE TITLE
Footnote 22

### ISSUE THREAD

**Issue by frankhmcnally** [WhiteHouse/source-code-policy#43]
In Section 3, Software Procurement Considerations, footnote 22 is crucial. Wondering if this doesn't deserve more attention in the policy, for fear that footnotes aren't always read with great consistency?

Not sure if this qualifies as an "issue" or not and apologies if this has been discussed. Relatively new to using GitHub discussion boards.

**Comment by AlvandSalehi** [comment]
@frankhmcnally Thanks for your comment!  Footnote 22 falls under Section 4 (Government-Wide Code Reuse).  Is that the footnote you're referring to?

**Comment by frankhmcnally** [comment]
@AlvandSalehi oops I think I made a mistake. I intended to refer to footnote 19 in Section 3, the one that encourages agencies to consider the OSS software license and its implications. Sorry about that! You could take that one footnote 19 alone and probably write an entire policy out of it!

**Comment by chasingamy** [comment]
@AlvandSalehi @frankhmcnally - Please see [Public Issue #75 ](https://github.com/WhiteHouse/source-code-policy/issues/75), now fixed and closed -- there was a discrepancy between the footnotes in the PDF of the policy document and the policy document posted on the website. They are now synced up. Apologies for any confusion!

**Comment by royfielding** [comment]
I agree with the original comment that what is now footnote [19](https://sourcecode.cio.gov/Procurement/#fn19):

> 19 For purposes of Federal IT acquisitions, OSS must be considered a commercial item and be given appropriate statutory preference per 41 U.S.C. §103 (1)(B), so long as the OSS product is available for license to the general public and meets the other terms therein. When using or modifying OSS, covered agencies are strongly encouraged to consider which license is associated with the software. Licenses affect how the work can be used, modified, and how derivative works must be treated. Agencies must comply with the terms of the licensed work. Government employees and their covered agencies are encouraged to improve the OSS they use and push those fixes to the appropriate code repository. This practice benefits all users of the software because those changes can be distributed widely. This work must follow the terms of the license of the original work. For further guidance, covered agencies should look to Project Open Source at https://project-open-source.cio.gov.

really deserves its own subsection. It is a good summary.
