### ISSUE TITLE
Request for comment acknowledgement

### ISSUE THREAD

**Issue by OpenGlobe** [WhiteHouse/source-code-policy#44]
First, this is fantastic!  

Second - I'd like to request what I hope is a simple procedural point in processing feedback solicited through these Github issues.

The observation that I had from a previous solicitation for comments request using Github was that I don't recall there was indication that anyone read the issue after it had been submitted.  It would be nice to have the equivalent of what hopefully happens after you send a letter to Congress - there's some indication that the letter has been opened and read.

What I'd like to suggest is simple tagging and / or categorization of comments into general themes as a way to acknowledge that someone has read them. 

Thanks!  Again, this is a fantastic effort.

**Comment by jlberryhill** [comment]
Thanks, @OpenGlobe! I can assure you that we take a look at each comment. I'll discuss this with the team and see if there's a way we can mark them to acknowledge that they have been read.

**Comment by OpenGlobe** [comment]
Great - thanks for considering it!

**Comment by konklone** [comment]
Perhaps you can use GitHub's emoji reactions. :)
