### ISSUE TITLE
Public Domain code and licensing

### ISSUE THREAD

**Issue by malanthomasii** [WhiteHouse/source-code-policy#46]
As is noted in the policy, code written by an employee of the government in the course of their duties is not copyrightable and thus would be released as public domain. However, it is worth remembering that this noncopyrightability is a specific effect of _United States_ copyright law and would not necessarily apply abroad.\* This is particularly important given that national-level use cases will naturally be of interest to foreign government users. Therefore, a fallback license should be prepared for those foreign users who will need one. Given that the code is otherwise public domain, a CC0 license would appear to be appropriate and avoid confusion.

It would, of course, be wildly inappropriate to use an open source release or open source development with non-employee contributions to impose a license on the code that is more restrictive than it would otherwise have (i.e., to domestically employ a non-public domain license on any codebase primarily developed in-house by federal employees).

*Wonk aside: The only common exceptions would be countries that both observe the rule of the shorter term and consider noncopyrightability in the country of origin to be equivalent to a zero-length term . . . and any programmer should know better than to assume that what happens when you compare an empty set with a numerical value will be the same in all languages and environments. ;)

**Comment by ghost** [comment]
Good point and agree on cc0 license in those cases.

**Comment by ascott1** [comment]
> Given that the code is otherwise public domain, a CC0 license would appear to be appropriate and avoid confusion.

This is exactly how the CFPB handles licensing. Here is our default [TERMS.md](https://github.com/cfpb/open-source-project-template/blob/master/TERMS.md).

**Comment by skybristol** [comment]
Not to put too fine a point on it, but the [CC0 Universal](https://creativecommons.org/publicdomain/zero/1.0/) designation is actually a waiver of copyright, not a license designation itself. Whether or not that designation is respected outside US borders doesn't matter all that much in that we've already waived all rights and don't/can't really care what happens with the code from that point.

The bummer of in, in some ways, is that Federal employees do write some pretty darn good code, and it would be nice to put something like a [CC-BY](https://creativecommons.org/licenses/by/2.0/) on that code to hopefully get some recognition for that good work occasionally. So, the going notions include putting DOIs on the code, listing citable code in various catalogs and indexes, and hoping that some folks cite the code as a matter of courtesy OR running live code projects via GitHub and elsewhere that get others engaged in the work and hopefully talking about some of the good things that taxpayer dollars fund.

**Comment by malanthomasii** [comment]
@skybristol The public license fallback in CC0 (§ 3 of the [full legal text](https://creativecommons.org/publicdomain/zero/1.0/legalcode)) is actually **increcredibly** important in this context because many of the covered rights—particularly "neighboring" rights—are in many foreign jurisdictions non-waivable as a matter of law, and in those places the waiver is meaningless.

"Whether or not that designation is respected outside US borders" matters a heck of a lot to people outside U.S. borders, particularly when those people are working for foreign governments that don't, as a matter of policy, like publicly breaking the law. If we didn't care what happens with the code at that point, we wouldn't be pushing for open source; it's because we want something to happen with the code at that point that we're discussing this at all.

I do appreciate your argument for CC-BY, though. If this were almost any other context I might agree, but some of the code's public domain domestically anyway, and it feels wrong to use Creative Commons to make something _less_ free. "A cite would be nice" is still a perfectly appropriate request to make on a more informal level, though. (A hint to whomever's editing the actual policy language. . . .)

**Comment by royfielding** [comment]
CC0 is not an open source license and is not appropriate for use with software. It would be **far better** for the government to simply state that the software is public domain and may also be redistributed under any open source license. I don't think it matters, in this case, whether "open source license" is defined by OSI or by some government procurement office.

However, more formality is required when it comes to accepting contributions from outside the government agencies. At a minimum, I think the government needs inbound licensing policies along the same lines as Apache, since it otherwise risks propagating intellectual property restrictions to downstream recipients of the code. For that reason, I would suggest adopting either a [contributor license](https://www.apache.org/licenses/icla.txt) that anyone can agree to when contributing or an open source license that includes default terms for how contributions shall be licensed.
