### ISSUE TITLE
“Acquisition Agility Act” H. R. 4741

### ISSUE THREAD

**Issue by johnmod3** [WhiteHouse/source-code-policy#49]
for reference, worth a read thru, applies to DoD, but interesting: 

https://www.congress.gov/bill/114th-congress/house-bill/4741/text?q=%7B%22search%22%3A%5B%22thornberry+and+acquisition%22%5D%7D&resultIndex=1

A BILL
To amend title 10, United States Code, to provide for modular open system architecture in major defense acquisition programs, and for other purposes.

Be it enacted by the Senate and House of Representatives of the United States of America in Congress assembled,

SECTION 1. SHORT TITLE; TABLE OF CONTENTS.
(a) Short Title.—This Act may be cited as the “Acquisition Agility Act”.

(b) Table Of Contents.—The table of contents for this Act is as follows:

https://www.congress.gov/bill/114th-congress/house-bill/4741/text?q=%7B%22search%22%3A%5B%22thornberry+and+acquisition%22%5D%7DresultIndex=1#toc-H74F7D8891B75449181FFD4A6628F6A9F
https://www.congress.gov/bill/114th-congress/house-bill/4741/text?q=%7B%22search%22%3A%5B%22thornberry+and+acquisition%22%5D%7DresultIndex=1#toc-HB695783D841843639CF366ECA402885D
https://www.congress.gov/bill/114th-congress/house-bill/4741/text?q=%7B%22search%22%3A%5B%22thornberry+and+acquisition%22%5D%7DresultIndex=1#toc-H8512AA9AE79B4CFA9DFAB702FB637790
https://www.congress.gov/bill/114th-congress/house-bill/4741/text?q=%7B%22search%22%3A%5B%22thornberry+and+acquisition%22%5D%7DresultIndex=1#toc-HFC037E86B4D4441BA8DF6FC5078A60D5
https://www.congress.gov/bill/114th-congress/house-bill/4741/text?q=%7B%22search%22%3A%5B%22thornberry+and+acquisition%22%5D%7DresultIndex=1#toc-H0E70B36B69744F3B8262D9206247DE46
https://www.congress.gov/bill/114th-congress/house-bill/4741/text?q=%7B%22search%22%3A%5B%22thornberry+and+acquisition%22%5D%7DresultIndex=1#toc-HC1D9ED4F5828482C8843B81DC9F265A6

SEC. 2. MODULAR OPEN SYSTEM ARCHITECTURE IN DEVELOPMENT OF MAJOR WEAPON SYSTEMS.
(a) In General.—Part IV of subtitle A of title 10, United States Code, is amended by inserting after chapter 144A the following new chapter:

“CHAPTER 144B—WEAPON SYSTEMS DEVELOPMENT AND RELATED MATTERS
“Subchapter ............................................................................................. Sec.
“I. Modular Open System Architecture in Development of Weapon Systems 2446a
“II. Weapon System Component Development, Prototyping, and Deployment 2447a
“III. Cost, Schedule, and Performance of Major Defense Acquisition Programs   2448a
“SUBCHAPTER I—MODULAR OPEN SYSTEM ARCHITECTURE IN DEVELOPMENT OF WEAPON SYSTEMS

https://www.congress.gov/bill/114th-congress/house-bill/4741/text?q=%7B%22search%22%3A%5B%22thornberry+and+acquisition%22%5D%7DresultIndex=1#toc-H4CE0EF8F601A43BE82649025656E3EFC
https://www.congress.gov/bill/114th-congress/house-bill/4741/text?q=%7B%22search%22%3A%5B%22thornberry+and+acquisition%22%5D%7DresultIndex=1#toc-H4CE0EF8F601A43BE82649025656E3EFC
https://www.congress.gov/bill/114th-congress/house-bill/4741/text?q=%7B%22search%22%3A%5B%22thornberry+and+acquisition%22%5D%7DresultIndex=1#toc-H2A64CD51C19941FB9A9519C8C07B1076
https://www.congress.gov/bill/114th-congress/house-bill/4741/text?q=%7B%22search%22%3A%5B%22thornberry+and+acquisition%22%5D%7DresultIndex=1#toc-H18AC81629CBD462985D30D785D3AB5D7
https://www.congress.gov/bill/114th-congress/house-bill/4741/text?q=%7B%22search%22%3A%5B%22thornberry+and+acquisition%22%5D%7DresultIndex=1#toc-H1D7DCA99835149CC97A814E88E98CA86

“§ 2446a. Requirement for modular open system architecture in major defense acquisition programs; definitions
“(a) Modular Open System Architecture Requirement.—A major defense acquisition program initiated after October 1, 2018, shall be designed and developed with a modular open system architecture to enable incremental development.

“(b) Definitions.—In this chapter:

“(1) The term ‘modular open system architecture’ means, with respect to a major defense acquisition program, an integrated business and technical strategy that—

“(A) employs a modular design and uses, if available and suitable, widely supported and consensus-based standards for major system interfaces between the major system platform being developed under the program and its major system components;

“(B) is subjected to testing to ensure major system interfaces comply with widely supported and consensus-based standards; and

“(C) uses a system architecture that allows major system components to be incrementally added, removed, or replaced throughout the life cycle of the major system platform to afford opportunities for enhanced competition and innovation while yielding—

“(i) significant cost savings or avoidance;

“(ii) schedule reduction; or

“(iii) increased interoperability.

“(2) The term ‘major system platform’ means the structure of a major weapon system on which a major system component can be mounted or integrated.

“(3) The term ‘major system component’—

“(A) means a subsystem or assembly that can be mounted or installed on a major system platform through well-defined, open major system interfaces; and

“(B) includes a subsystem or assembly that is likely to have additional capability requirements, is likely to change because of evolving technology or threat, is needed for interoperability, facilitates incremental deployment of capabilities, or is expected to be replaced.

“(4) The term ‘major system interface’ means a shared boundary between a major system platform and its major system components, defined by various characteristics pertaining to—

“(A) physical standards for mounting major system components;

“(B) functional standards for integrating major system components, such as electrical, radio frequency, data, or software elements; and

“(C) open intellectual property rights consistent with section 2320 of this title.

“(5) The term ‘program capability document’ means, with respect to a major defense acquisition program, a document that specifies capability requirements for the program, such as a capability development document or a capability production document.

“(6) The terms ‘program cost target’ and ‘fielding target’ have the meanings provided in section 2448a(a) of this title.

“(7) The term ‘major defense acquisition program’ has the meaning provided in section 2430 of this title.

“(8) The term ‘major weapon system’ has the meaning provided in section 2379(f) of this title.

“§ 2446b. Requirement to address modular open system architecture in program capabilities development and acquisition weapon system design
“(a) Program Capability Document.—A program capability document for a major defense acquisition program shall identify and characterize—

“(1) the extent to which requirements for system performance are likely to evolve during the life cycle of the system because of evolving technology, threat, or interoperability needs; and

“(2) for requirements that are expected to evolve, the minimum acceptable capability that will be available upon initial operating capability of the major defense acquisition program.

“(b) Analysis Of Alternatives.—The Director of Cost Assessment and Performance Evaluation, in formulating study guidance for analyses of alternatives for major defense acquisition programs and performing such analyses under section 139a(d)(4) of this title, shall ensure that any such analysis for a major defense acquisition program includes consideration of an incremental development approach and modular open system architecture.

“(c) Acquisition Strategy.—An acquisition strategy for a major defense acquisition program, as required under section 2431a of this title, shall—

“(1) clearly describe the modular open system architecture to be used for the program;

“(2) differentiate between the major system platform and major system components being developed under the program;

“(3) clearly describe the incremental approach to major system components that are anticipated to meet requirements for system performance;

“(4) identify additional major system components that may be added later in the life cycle of the major system platform; and

“(5) clearly describe how intellectual property and related issues, such as data deliverables and license rights, that are necessary to support a modular open system architecture will be addressed.

“(d) Request For Proposals.—The milestone decision authority for a major defense acquisition program shall ensure that a request for proposals for the development or production phases of the program shall address the modular open system architecture to be used.

“(e) Milestone B.—A major defense acquisition program may not receive Milestone B approval under section 2366b of this title until the milestone decision authority determines in writing that—

“(1) the program incorporates a modular open system architecture with clearly defined major system interfaces between the major system platform and major system components to be developed under the program;

“(2) such major system interfaces are consistent with the widely supported and consensus-based standards that exist at the time of the milestone decision, unless such standards are unavailable or unsuitable for particular major system interfaces; and

“(3) the Government has arranged to obtain appropriate and necessary intellectual property rights with respect to such major system interfaces upon completion of the development of the major system platform.

“§ 2446c. Requirements relating to availability of major system interfaces and support for modular open system architecture
“The Secretary of each military department shall—

“(1) coordinate with the other military departments, the defense agencies, defense and other private sector entities, and national standards-setting organizations with respect to the identification, development, and maintenance of major system interfaces and standards for use in major system platforms, where practicable;

“(2) ensure that major system interfaces incorporate commercial standards to the maximum extent practicable;

“(3) ensure sufficient systems engineering and development expertise and resources are available to support modular open system architecture in requirements development and acquisition program planning;

“(4) ensure that necessary planning, programming, and budgeting resources are provided to identify, develop, and maintain modular open system architecture and associated major system interfaces; and

“(5) ensure adequate training in modular open system architecture is provided to members of the requirements and acquisition workforce.

“§ 2446d. Requirement to include modular open system architecture in Selected Acquisition Reports
“For each major defense acquisition program that receives Milestone B approval after October 1, 2018, a description of the key elements of the modular open system architecture or, if a modular open system architecture was not used, the rationale for not using such an architecture, shall be submitted to the congressional defense committees with the first Selected Acquisition Report required under section 2432 of this title for the program.”.

(b) Clerical Amendment.—The table of chapters for title 10, United States Code, is amended by adding after the item relating to chapter 144A the following new item:

“144B. Weapon Systems Development and Related Matters ..................  2446a”.
(c) Conforming Amendment.—Section 2366b(a)(3) of such title is amended—

(1) by striking “and” at the end of subparagraph (K); and

(2) by inserting after subparagraph (L) the following new subparagraph:

“(M) the requirements of section 2446b(e) of this title are met; and”.

(d) Effective Date.—Subchapter I of chapter 144B of title 10, United States Code, as added by subsection (a), shall take effect on October 1, 2016.

SEC. 3. WEAPON SYSTEM COMPONENT DEVELOPMENT, PROTOTYPING, AND DEPLOYMENT.
(a) In General.—Chapter 144B of title 10, United States Code, as added by section 2, is further amended by adding at the end the following new subchapter:

https://www.congress.gov/bill/114th-congress/house-bill/4741/text?q=%7B%22search%22%3A%5B%22thornberry+and+acquisition%22%5D%7DresultIndex=1#HB6110B544DDF4061B974A6B10A3270FB

https://www.congress.gov/bill/114th-congress/house-bill/4741/text?q=%7B%22search%22%3A%5B%22thornberry+and+acquisition%22%5D%7DresultIndex=1#toc-H9CAB53E4530649A8B164C66A8A62C301
https://www.congress.gov/bill/114th-congress/house-bill/4741/text?q=%7B%22search%22%3A%5B%22thornberry+and+acquisition%22%5D%7DresultIndex=1#toc-H9CAB53E4530649A8B164C66A8A62C301
https://www.congress.gov/bill/114th-congress/house-bill/4741/text?q=%7B%22search%22%3A%5B%22thornberry+and+acquisition%22%5D%7DresultIndex=1#toc-HABE19F502842446B99855593DC788188
https://www.congress.gov/bill/114th-congress/house-bill/4741/text?q=%7B%22search%22%3A%5B%22thornberry+and+acquisition%22%5D%7DresultIndex=1#toc-HE90031B4F5BF4E3EB45EC467E6AF69A8
https://www.congress.gov/bill/114th-congress/house-bill/4741/text?q=%7B%22search%22%3A%5B%22thornberry+and+acquisition%22%5D%7DresultIndex=1#toc-H219F73092674438B8B4037648CD07A64
https://www.congress.gov/bill/114th-congress/house-bill/4741/text?q=%7B%22search%22%3A%5B%22thornberry+and+acquisition%22%5D%7DresultIndex=1#toc-H020396E4034A448485D2FCC5ACC62B74
https://www.congress.gov/bill/114th-congress/house-bill/4741/text?q=%7B%22search%22%3A%5B%22thornberry+and+acquisition%22%5D%7DresultIndex=1#toc-H7776E4394F4141138652B8AD6FDFF381

“§ 2447a. Technology development in the acquisition of major weapon systems
“Technology shall be developed in a major defense acquisition program that is initiated after October 1, 2018, only if the milestone decision authority for the program determines with a high degree of confidence that such development will not delay the fielding target of the program. If the milestone decision authority does not make such determination for a major system component being developed under the program, the milestone decision authority shall ensure that technology related to the major system component shall be sufficiently matured separate from the major defense acquisition program using the prototyping authorities of this section or other authorities, as appropriate.

“§ 2447b. Weapon system component prototype projects: display of budget information
“(a) Requirements For Budget Display.—In the defense budget materials for any fiscal year after fiscal year 2017, the Secretary of Defense shall, with respect to advanced component development and prototype activities (within the research, development, test, and evaluation budget), set forth separately the amounts requested for each of the following:

“(1) Acquisition programs of record.

“(2) Experimentation and rapid prototyping of weapon system components or other technologies and subsystems.

“(3) Other budget line items as determined by the Secretary of Defense.

“(b) Additional Requirements.—For purposes of subsection (a)(2), the amounts requested for experimentation and rapid prototyping of weapon system components or other technologies and subsystems shall be—

“(1) displayed in separate budget lines structured into either capability or weapon system component portfolios that reflect the priority areas for prototype projects; and

“(2) justified with general descriptions of the types of capability areas and technologies being funded or expected to be funded during the fiscal year concerned.

“(c) Definitions.—In this section, the terms ‘budget’ and ‘defense budget materials’ have the meaning given those terms in section 234 of this title.

“§ 2447c. Weapon system component prototype projects: oversight
“(a) Establishment.—The Secretary of each military department shall establish or appoint an oversight board or similar group of senior advisors for managing prototype projects for weapon system components and other technologies and subsystems, including the use of funds for such projects, within the military department concerned.

“(b) Membership.—Each oversight board shall be comprised of senior officials with—

“(1) expertise in requirements; research, development, test, and evaluation; acquisition; or other relevant areas within the military department concerned; and

“(2) awareness of the component capability requirements of major weapon systems, including scheduling and fielding goals for such component capabilities.

“(c) Functions.—The functions of each oversight board are as follows:

“(1) To issue a strategic plan every three years that prioritizes the capability and weapon system component portfolio areas for conducting prototype projects, based on assessments of high priority warfighter needs, capability gaps on existing major weapon systems, opportunities to incrementally integrate new components into major weapon systems, and technologies that are expected to be sufficiently mature to prototype within 3 years.

“(2) To annually recommend funding levels for weapon system component prototype projects across capability or weapon system component portfolios.

“(3) To annually recommend to the service acquisition executive of the military department concerned specific weapon system component prototype projects, subject to the requirements and limitations in section 2447d of this title.

“(4) To ensure projects are managed by experts within the Department of Defense who are knowledgeable in research, development, test, and evaluation and who are aware of opportunities for incremental deployment of component capabilities to major weapon systems.

“(5) To ensure projects are conducted in a manner that allows for appropriate experimentation and technology risk.

“(6) To ensure necessary technical, contracting, and financial management resources are available to support each project.

“(7) To submit to the congressional defense committees a semiannual notification that includes the following:

“(A) A description of each weapon system component prototype project initiated during the preceding six months, including an explanation of each project and its required funding.

“(B) A description of the results achieved from weapon system component prototype projects completed and tested during the preceding six months.

“§ 2447d. Requirements and limitations for weapon system component prototype projects
“(a) Limitation On Prototype Project Duration.—A prototype project shall be completed within three years of its initiation.

“(b) Merit-Based Selection Process.—A prototype project shall be selected by the service acquisition executive of the military department concerned through a merit-based selection process that identifies the most promising and cost-effective prototypes that address a high priority warfighter need and are expected to be successfully demonstrated in a relevant environment.

“(c) Type Of Transaction.—Prototype projects shall be funded through contracts, cooperative agreements, or other transactions.

“(d) Funding Limit.—(1) Each prototype project may not exceed a total amount of $5,000,000 (based on fiscal year 2017 constant dollars), unless—

“(A) the Secretary of the military department, or the Secretary’s designee, approves a larger amount of funding for the project, not to exceed $25,000,000; and

“(B) the Secretary, or the Secretary’s designee, submits to the congressional defense committees, within 30 days after approval of such funding for the project, a notification that includes—

“(i) a description of the project;

“(ii) expected funding for the project; and

“(iii) a statement of the anticipated outcome of the project.

“(2) The Secretary of Defense may adjust the amounts (and the base fiscal year) provided in paragraph (1) on the basis of Department of Defense escalation rates.

“§ 2447e. Mechanisms to speed deployment of successful weapon system component prototypes
“(a) Selection Of Prototype Project For Production.—A weapon system component or technology prototype project may be selected by the service acquisition executive of the military department concerned for a follow-on production contract or other transaction without the use of competitive procedures, notwithstanding the requirements of section 2304 of this title, if—

“(1) a prototype project addresses a high priority warfighter need;

“(2) competitive procedures were used for the selection of parties for participation in the prototype project;

“(3) the participants in the project successfully completed the project provided for in the transaction; and

“(4) the prototype was demonstrated in a relevant environment.

“(b) Special Transfer Authority.—(1) The Secretary of a military department may transfer funds that remain available for obligation in procurement appropriation accounts of the military department to fund the low-rate initial production of a prototype until required funding for full-rate production can be submitted and approved through the regular budget process of the Department of Defense.

“(2) The funds transferred under this subsection to be used for production of a prototype shall be for a period not to exceed two years, the amount for such period may not exceed $10,000,000, and the special transfer authority provided in this subsection may not be used more than once to fund procurement of a particular prototype.

“(3) The special transfer authority provided in this subsection is in addition to any other transfer authority available to the Department of Defense.

“(c) Notification To Congress.—Within 30 days after the service acquisition executive of a military department selects a weapon system component or technology prototype project for a follow-on production contract or other transaction, the service acquisition executive shall notify the congressional defense committees of the selection.

“§ 2447f. Definition of weapon system component
“In this subchapter, the term ‘weapon system component’ has the meaning provided the term ‘major system component’ in section 2446a of this title.”.

(b) Effective Date.—Subchapter II of chapter 144B of title 10, United States Code, as added by subsection (a), shall take effect on October 1, 2016.

SEC. 4. COST, SCHEDULE, AND PERFORMANCE OF MAJOR DEFENSE ACQUISITION PROGRAMS.
(a) In General.—Chapter 144B of title 10, United States Code, as added by section 2, is amended by adding at the end the following new subchapter:

https://www.congress.gov/bill/114th-congress/house-bill/4741/text?q=%7B%22search%22%3A%5B%22thornberry+and+acquisition%22%5D%7DresultIndex=1#H56EEFE4AECCC442E90334AF7D9931936

https://www.congress.gov/bill/114th-congress/house-bill/4741/text?q=%7B%22search%22%3A%5B%22thornberry+and+acquisition%22%5D%7DresultIndex=1#toc-HC82692A908DB43ECB31EF79365B30F37
https://www.congress.gov/bill/114th-congress/house-bill/4741/text?q=%7B%22search%22%3A%5B%22thornberry+and+acquisition%22%5D%7DresultIndex=1#toc-HC82692A908DB43ECB31EF79365B30F37
https://www.congress.gov/bill/114th-congress/house-bill/4741/text?q=%7B%22search%22%3A%5B%22thornberry+and+acquisition%22%5D%7DresultIndex=1#toc-HCCED7E27A4724F20827FC31C80A8B426
https://www.congress.gov/bill/114th-congress/house-bill/4741/text?q=%7B%22search%22%3A%5B%22thornberry+and+acquisition%22%5D%7DresultIndex=1#toc-H8546FE228A084E1081B67D1CD57F3B63

“§ 2448a. Program cost and fielding targets in planning major defense acquisition programs
“(a) Program Cost And Fielding Targets.—Before Milestone A approval is granted for a major defense acquisition program, the Secretary of Defense shall ensure the program will be affordable and fielded when needed by establishing targets for—

“(1) the program acquisition unit cost (referred to in this section as the ‘program cost target’; and

“(2) the date for initial operational capability (referred to in this section as the ‘fielding target’).

“(b) Considerations.—In establishing targets under subsection (a) for the program, the Secretary of Defense shall consider each of the following:

“(1) The capability needs and timeframe specified in the initial capabilities document, opportunities for incremental deployment of capabilities, and minimum acceptable capability increments.

“(2) Resources available to fund the development, production, and life cycle of the program, using a reasonable estimate of future defense budgets.

“(3) Procurement quantity objectives.

“(4) Trade-offs among cost, schedule, technical risk, and performance objectives identified in the analysis of alternatives required under section 2366a of this title.

“(5) The independent cost estimate prepared or approved under section 2334(a)(6) of this title.

“(6) The independent technical risk assessment conducted or approved under section 2448b of this title.

“(c) Delegation.—The responsibilities of the Secretary of Defense in subsection (a) may be delegated only to the Deputy Secretary of Defense or the Under Secretary of Defense for Acquisition, Technology, and Logistics.

“(d) Definitions.—In this section:

“(1) The term ‘program acquisition unit cost’ has the meaning provided in section 2432(a) of this title.

“(2) The term ‘initial capabilities document’ has the meaning provided in section 2366a(d)(2) of this title.

“§ 2448b. Independent technical risk assessments
“(a) In General.—The Under Secretary of Defense for Acquisition, Technology, and Logistics shall conduct or approve an independent technical risk assessment for a major defense acquisition program—

“(1) before any decision to grant milestone approval pursuant to section 2366a or 2366b of this title;

“(2) before any decision to enter into low-rate initial production or full-rate production; and

“(3) at any other time considered appropriate by the Under Secretary.

“(b) Categorization Of Technical Risk Levels.—The Under Secretary shall issue guidance and a framework for categorizing the degree of technical risk in a major defense acquisition program and a major automated information system.

“§ 2448c. Adherence to requirements and thresholds in major defense acquisition programs
“(a) Capabilities Determination.—The Secretary of the military department concerned shall ensure that the capability development document supporting a Milestone A or subsequent milestone for a major defense acquisition program may not be submitted to the Joint Requirements Oversight Council for approval until the Chief of the armed force concerned determines in writing that the requirements in the document are necessary and realistic in relation to the program cost and fielding targets established under section 2448a(a) of this title.

“(b) Compliance With Targets Before Milestone B Approval.—A major defense acquisition program may not receive Milestone B approval until the milestone decision authority for the program determines in writing that the estimated program acquisition unit cost and the estimated date for initial operational capability for the baseline description for the program (established under section 2435) do not exceed the program cost and fielding targets established under section 2448a(a) of this title. If such estimated cost is higher than the program cost target or if such estimated date is later than the fielding target, the milestone decision authority may request that the Secretary of Defense increase the program cost target or delay the fielding target, as applicable.”.

(b) Effective Date.—Subchapter III of chapter 144B of title 10, United States Code, as added by subsection (a), shall apply with respect to major defense acquisition programs that reach Milestone A after October 1, 2016.

(c) Modification Of Milestone Decision Authority.—Effective October 1, 2016, subsection (d) of section 2430 of title 10, United States Code, as added by section 825(a) of the National Defense Authorization Act for Fiscal Year 2016 (https://www.gpo.gov/fdsys/pkg/PLAW-114publ92/pdf/PLAW-114publ92.pdf; 129 Stat. 907), is amended—

(1) in paragraph (2)(A), by inserting “subject to paragraph (5),” before “the Secretary determines”; and

(2) by adding at the end the following new paragraph:

“(5) The authority of the Secretary of Defense to designate an alternative milestone decision authority for a program with respect to which the Secretary determines that the program is addressing a joint requirement, as set forth in paragraph (2)(A), shall apply only for a major defense acquisition program that reaches Milestone A after October 1, 2016, and before October 1, 2019.”.

SEC. 5. TRANSPARENCY IN MAJOR DEFENSE ACQUISITION PROGRAMS.
(a) Reports On Milestone Decision Metrics.—Subchapter III of chapter 144B of title 10, United States Code, as added by section 2, is amended by adding at the end the following new section:

“§ 2448d. Reports on milestone decision metrics

“(a) Report On Milestone A.—Not later than 15 days after granting Milestone A approval for a major defense acquisition program, the milestone decision authority for the program shall provide to the congressional defense committees a brief summary report that contains the following:

“(1) The program cost and fielding targets established by the Secretary of Defense under section 2448a(a) of this title.

“(2) The cost and schedule estimates for the program conducted by the military department concerned.

“(3) The independent cost estimate for the program conducted or approved under section 2334(a)(6) of this title, and any independent schedule estimate conducted for the program.

“(4) A summary of the technical risks associated with the program, as determined by the military department concerned.

“(5) A summary of the independent technical risk assessment conducted or approved under section 2448b of this title.

“(6) A summary of the sufficiency review conducted by the Director of Cost Assessment and Program Evaluation of the analysis of alternatives performed for the program (as referred to in section 2366a(b)(6) of this title).

“(7) Any other information the milestone decision authority considers relevant.

“(b) Report On Milestone B.—Not later than 15 days after granting Milestone B approval for a major defense acquisition program, the milestone decision authority for the program shall provide to the congressional defense committees a brief summary report that contains the following:

“(1) The program cost and fielding targets established by the Secretary of Defense under section 2448a(a) of this title.

“(2) The cost and schedule estimates for the program conducted by the military department concerned.

“(3) The independent cost estimate for the program conducted or approved under section 2334(a)(6) of this title, and any independent schedule estimate conducted for the program.

“(4) The cost and schedule estimates approved for the program by the milestone decision authority.

“(5) A summary of the technical risks associated with the program, as determined by the military department concerned.

“(6) A summary of the independent technical risk assessment conducted or approved under section 2448b of this title.

“(7) A list of critical technologies, if any, associated with the program, that have not been successfully tested in a relevant environment.

“(8) A statement of whether the preliminary design review for the program (referred to in section 2366b(a)(1) of this title) has been completed.

“(9) A statement of whether a modular open system architecture is being used for the program.

“(10) Any other information the milestone decision authority considers relevant.

“(c) Report On Milestone C.—Not later than 15 days after granting Milestone C approval for a major defense acquisition program, the milestone decision authority for the program shall provide to the congressional defense committees a brief summary report that contains the following:

“(1) The cost and schedule estimates for the program conducted by the military department concerned.

“(2) The independent cost estimate for the program conducted or approved under section 2334(a)(6) of this title, and any independent schedule estimate conducted for the program.

“(3) The cost and schedule estimates approved by the milestone decision authority for the program.

“(4) A summary of the production, manufacturing, and fielding risks associated with the program.

“(d) Additional Information.—At the request of any of the congressional defense committees, the milestone decision authority shall submit to the committee further information or underlying documentation for the information in a report submitted under subsection (a), (b), or (c), including the independent cost and schedule estimates and the independent technical risk assessments referred to in those subsections.”.

(b) Clerical Amendment.—The table of sections at the beginning of such subchapter is amended by adding at the end the following new item:

“2448d. Reports on milestone decision metrics.”.

SEC. 6. AMENDMENTS RELATING TO TECHNICAL DATA RIGHTS.
(a) Rights Relating To Item Or Process Developed Exclusively At Private Expense.—

(1) Subsection (a)(2)(C) of section 2320 of title 10, United States Code, is amended—

(A) by striking clause (ii) and inserting the following:

“(ii) relates to form, fit, function, or the external interface of an item or process with other items or processes, including any major system interface of a major system component with a major system platform or other major system component;”; and

(B) in clause (iii), by inserting after “or process data” the following: “, including data pertaining to a major system component”.

(2) Subsection (a)(2)(D)(i) of such section is amended—

(A) by inserting “or” at the end of subclause (I);

(B) by striking subclause (II); and

(C) by redesignating subclause (III) as subclause (II).

(b) Rights Relating To Item Or Process Developed In Part With Federal Funds And In Part At Private Expense.—Subsection (a)(2) of section 2320 of such title is further amended—

(1) by redesignating subparagraphs (F) and (G) as subparagraphs (G) and (H), respectively;

(2) in subparagraph (E), by striking “In the case of” and inserting “Except as provided in subparagraph (F), in the case of”; and

(3) by inserting after subparagraph (E) the following new subparagraph (F):

“(F) Notwithstanding subparagraph (E), in the case of an external interface that is developed in part with Federal funds and in part at private expense, the United States shall have unlimited rights to—

“(i) use technical data pertaining to such external interface; or

“(ii) release or disclose the technical data to persons outside the government or permit the use of the technical data by such persons.”.

(c) Definitions.—Section 2320 of such title is further amended—

(1) in subsection (f), by inserting “Covered Government Support Contractor Defined.—” before “In this section”; and

(2) by adding at the end the following new subsection:

“(g) Additional Definitions.—In this section, the terms ‘major system platform’, ‘major system component’, and ‘major system interface’ have the meanings provided in section 2446a of this title.”.

(d) Government-Industry Advisory Panel Amendments.—Section 813(b) of the National Defense Authorization Act for Fiscal Year 2016 (https://www.gpo.gov/fdsys/pkg/PLAW-114publ92/pdf/PLAW-114publ92.pdf; 129 Stat. 892) is amended—

(1) by adding at the end of the paragraph (1) the following: “The panel shall develop recommendations for changes to sections 2320 and 2321 of title 10, United States Code, and the regulations implementing such sections.”;

(2) in paragraph (3)—

(A) by redesignating subparagraphs (D) and (E) as subparagraphs (E) and (F), respectively; and

(B) by inserting after subparagraph (C) the following new subparagraph (D):

“(D) Ensuring that the Department of Defense and Department of Defense contractors have the technical data rights necessary to support the modular open system architecture requirement set forth in section 2446a of title 10, United States Code, taking into consideration the distinct characteristics of major system platforms, major system interfaces, and major system components developed exclusively with Federal funds, exclusively at private expense, and with a combination of Federal funds and private expense.”; and

(3) in paragraph (4), by striking “September 30, 2016” and inserting “December 15, 2016”.

(e) Amendment Relating To Negotiated Rights For Item Or Process Developed With Mixed Funding.—Subsection (a)(2)(E) of section 2320 of title 10, United States Code, is further amended by striking the period at the end of the first sentence in the matter preceding clause (i) and all that follows through “establishment of any such negotiated rights shall” and inserting “and shall be based on negotiations between the United States and the contractor, except in any case in which the Secretary of Defense determines, on the basis of criteria established in the regulations, that negotiations would not be practicable. The establishment of such rights shall”.

(f) Amendment Relating To Deferred Ordering.—Subsection (b)(9) of section 2320 of such title is amended—

(1) by striking “at any time” and inserting “, until the date occurring five years after acceptance of the last item (other than technical data) under a contract or the date of contract termination, whichever is later,”;

(2) by striking “or utilized in the performance of a contract” and inserting “in the performance of the contract”; and

(3) by striking clause (ii) of subparagraph (B) and inserting the following:

“(ii) is described in subsection (a)(2)(C); and”.

**Comment by theplaz** [comment]
Sounds good in theory - however from my USDS experience I have seen top-down well-intentioned directives badly misinterpreted and making things worse.  We would need some further oversight to make sure things are correctly interpreted.
