### ISSUE TITLE
Email Comment: Comment on source code

### ISSUE THREAD

**Issue by OMBPublicComments** [WhiteHouse/source-code-policy#50]
[Submitted Tue 3/15/2016 10:14 AM]

Good Morning,

I have been working to obtain a customized software program with an outside federal agency who wants to share their information with us at no cost.  They are offering it to us without warranty and to receive this “as is” by a Memorandum of Agreement.  We have the IT support to implement the software on our end without having to go through a vendor to recreate something already accomplished by a federal agency.  However, we cannot get the support of our Special Counsel to agree on this because they believe we MUST pay for this.  Your draft policy is heading in the right direction; however, we would ike to see this happen sooner than later.  Any suggestions in the meantime?  Thank you.

Very Respectfully,
Melanie A. Murguia
Supervisory Personnel Security Specialist
Security Branch, National Labor Relations Board

**Comment by johnmod3** [comment]
simple: make a $ xxx payment for support, maybe 1 k?
