### ISSUE TITLE
Email Comment: Open source policy comment

### ISSUE THREAD

**Issue by OMBPublicComments** [WhiteHouse/source-code-policy#51]
[Received: Tue 3/15/2016 12:46 PM]

This should be hosted on a site that open sources their code.  Github is a closed source company.  Recommend gitlab, etc.

The irony is high.

Sent from my Windows Phone

[Sender Name: "Ace OfHearts"]

**Comment by aaronpava** [comment]
Sent from my Windows Phone

The irony is high.
