### ISSUE TITLE
Establish Government-endorsed OSS product  labelling scheme

### ISSUE THREAD

**Issue by rafael5** [WhiteHouse/source-code-policy#52]
To support the re-use of open source software between government agencies, it would be of great value to to have an online catalog of  F/OSS products that are already in use by other goverment agencies, and with description, licensing, and assessment, and guidance. As an example of such a catalog is the U.S. Department of Veterans Affairs software catalog:

http://www.va.gov/TRM/SearchPage.asp

=> If you filter this search for "open-source" the result is 718  Open-Source licensed software products that are endorsed for use in the U.S. Department of Veterans Affairs.

=> The VA Software Catalog may thus be a good starting place for a Federal Open-Source Software Catalog

The VA Catalog presents a list of assessed technologies and standards used to develop, operate, and maintain enterprise applications. Entries on this list have undergone a strategic assessment based upon the nature of the technology. Each entry contains guidance, along with any known applicable constraints, on the permissible range of technologies or standards that a VA user,  technical support team or project development team may select or shall use. The VA Catalog is not intended to direct procurements, although each entry contains available VA licensing information, if known.

**Comment by johnmod3** [comment]
there are these, I'd settled for just having: 
- Agency that funded the work 
- contract number 
- contractor
  in the ReadMe doc, getting folk to list their software doesn't happen, j

https://docs.google.com/spreadsheets/d/1-z0AiiGbiW8aCcXjupeHVoH_g5LadO2K2dmyIIPuaRY/edit#gid=622499267
- refs:
  https://docs.google.com/spreadsheets/d/125qQRASj2p_Z_PFvfvErAHRGpjqseeIdmVxYuLvZfHo/edit#gid=8

**Comment by rafael5** [comment]
The google docs above don't seem to have any government sponsorship or endorsement.

gov-oss.org            =>  website of  Red Hat Inc employee
civiccommons.org  =>  dead link

Nor is are they any links to any source code or code repository.

REQUIRED:  Links to the authoritative source code repositories of the developer of the software.

**Comment by johnmod3** [comment]
the google doc was started by some folk at nasa. DARPA has a catalog: http://opencatalog.darpa.mil/ - the market is too big for an official gov catalog

**Comment by rafael5** [comment]
"... the market is too big for an official gov catalog..."

This is why we have community-driven content.... Wikipedia :)

**Comment by johnmod3** [comment]
dev's don't use wikipedia, there was a github project that searched the repo's for us gov type project. Seems defunct

**Comment by mikeBeviBevi** [comment]
There are multiple efforts in individual federal agencies to gather this information and store it in a readily accessible data base.  I do not know of an effort to inventory these across agencies.

**Comment by rafael5** [comment]
This is why a Federal Interagency repository / index is needed - something that the Whitehouse CIO's office should establish and coordinate...

**Comment by AlvandSalehi** [comment]
@rafael5 @johnmod3 @mikeBeviBevi Thanks very much for contributing to this thread.

@johnmod3 Regarding your first comment, I'd like to hear more about why you think "contract number" and "contractor" should be included as potential fields in the ECI.  Do you think these are necessary for code discoverability?

**Comment by johnmod3** [comment]
@AlvandSalehi yes, since code is created by people and companies it good to have a ref. back to the creators. + helps discovery
