### ISSUE TITLE
Federal employees or Federal agreements

### ISSUE THREAD

**Issue by skybristol** [WhiteHouse/source-code-policy#54]
The language in the draft policy is a little ambiguous or less than perfectly clear on its applicability. It does state that it applies to code developed both by Federal employees and contracts, but then makes statements like the following under the objectives: "This applies only to software developed in the performance of a Federal agreement."

Many government employees, especially from agencies with a science or engineering mission, develop quite a lot of software directly in addition to software developed through Cooperative Agreements and other contracting vehicles. The policy could be improved by making this point clear and indicating that it applies to software developed by Federal employees and to contractors/partners under Federal agreements.

**Comment by s390guy** [comment]
The development of a Federal-wide OSS policy is valuable.  While an employee of a Federal agency, I failed to get the agency to engage in the development of such a policy. 

My commens focus primarily on the Federal employee aspect and in particular how the policy could clarify its relationship to software developed by them.

Software, as identified in the policy, written by Federal employees in the performance of their duties is in the public domain.  Such software can already be freely shared both within and without the Federal government.  Such software most likely lacks declarations that it is in the public domain or any mechanism for making such software available to others, within and without the Federal government.  Perhaps the the software inventories mentioned in the policy may facilitate discovery of such software.

Seemingly making such public domain software available to others would be consistent with the spirit of this policy and may in fact be an objective of it.  Clarifying how the public domain software written by Federal employees in the performance of their duties relates to this policy would be desirable.  Can making such software available aid in meeting the 20% objective and would it apply only to new development, enhancements of existing public domain software or existing as-is?

OSS policies, where the topic is discussed, encourage the inclusion of what an employee may do with regards to participation in open source efforts outside of their prescribed duties as employees.  Clarifying that would be helpful.
