### ISSUE TITLE
Since complexity comes with learning-curve and often maintenance costs, a strategy should be developed toward using and creating very small code

### ISSUE THREAD

**Issue by benrayfield** [WhiteHouse/source-code-policy#57]
Without sacrificing too much of speed, reliability, and other concerns, it is important to think longterm about the complexity of systems. Governments, handling so many things at once, tend to become so big that nobody understands more than small parts, so its especially important here to plan longterm to keep things simple and define measures and rewards for it.

**Comment by davidjh78** [comment]
While simple is good, small isn't always possible. I think the key is to keep the code modular with well defined, well documented, standard interfaces (see issue 61).
