### ISSUE TITLE
Strongly encourage use of Open Standards and modular architectures

### ISSUE THREAD

**Issue by camerons** [WhiteHouse/source-code-policy#61]
Very closely related to the benefits of Open Source Software, is the adoption of Open Standards.
Open Standards facilitates interoperability between applications and organisations, mitigates risk of vendor lock-in and obsolescence, and is usually widely adopted by Open Source applications.
This policy should include reference to Open Standards, including recommending why standards should be adopted where they exist.
Refer to: http://mil-oss.org/resources/books/open-technology-development which includes:
"Use/modify/create open standards, in that order." It also defines an Open Standard.

**Comment by mhogeweg** [comment]
:+1: to Open Standards.

On December 9, 2015, OSTP released a Request for Information (RFI) soliciting public input on the United States Group on Earth Observations ([USGEO](https://www.whitehouse.gov/administration/eop/ostp/nstc/committees/cenrs/usgeo)) [Draft Common Framework for Earth-Observation Data](https://www.whitehouse.gov/sites/default/files/microsites/ostp/common_framework_for_earth_observation_data_draft_120215.pdf) (CFEOD). 

From the draft framework document: 

> To use a plumbing analogy, the recommendations in this document address the pipes and pumps used to deliver water from its source. The purpose of the CFEOD is not to build the faucets and spigots actually used to access the water, but rather to standardize parameters such as pipe diameter. This approach makes it so that people designing and building faucets and
> spigots know how to connect to the plumbing and makes it easier to design systems that combine water from multiple sources since the pipes are compatible, encouraging creativity and new innovations.

Understanding what standards exist and applying them will increase ability of connecting pre-existing modules, not to mention saves various trips to the home improvement store...

**Comment by davidjh78** [comment]
I think this is even more important than open source code itself. Code is modular and comprised of  well defined components with well defined functions and interfaces. This should include internal interfaces between components where possible and appropriate, as well as external interfaces. It is also very important to specify that open source data formats should be used, so that data produced by and used by applications can easily be interchanged.

**Comment by camerons** [comment]
davidjh78, I fully agree on the need for "open source data formats". The definition of Open Standards I've worked with cover both "data formats" as well as APIs to applications and web services. As such, I think "open standards" is inclusive of "open data formats".
