### ISSUE TITLE
Email Comment: Comment on Open Source Initiative

### ISSUE THREAD

**Issue by OMBPublicComments** [WhiteHouse/source-code-policy#67]
[Email comment, received: Monday, 3/21/2016, 4:07pm EDT]

My name is Robert David Steele. I started the Open Source Intelligence (OSINT) revolution in 1988, and because I was not listened to, today we have a secret intelligence community that has wasted $1 trillion (an average of $40 billion a year over 25 years) and that provides, "at best," according to General Tony Zinni, USMC, then Commanding General of the US Central Command engaged in two wars and 12 joint task forces, 4% (FOUR PERCENT) of what a top government decider needs in the way of decision-support. It could also be suggested that because we have failed to make the most of OSINT in support of strategy, policy, acquisition (45% documented waste in the Pentagon), and operations (75% documented waste in Afghanistan, $4 trillion wasted on the basis of 935 now documented lies that the secret intelligence world refused to challenge in public) the USA today is headed  toward being a  Third World country on the verge of revolution. Put bluntly, the US Government has refused to be serious about "open" since 1988 when I started this revolution, and also refused to be serious about cyber-security since 1994 when I sent the first letter to the White House and NSA was allowed to sabotage security across the US communications and computer industry, with the active complicity of the CEOs of major IT companies.

In 2012 I wrote [The Open Source Everything Manifesto: Transparency, Truth, & Trust](http:/www.amazon.com/exec/obidos/ASIN/1583944435/ossnet-20), subsequently featured in a profile by [Nafeez Ahmed in The Guardian](http:/www.theguardian.com/environment/earth-insight/2014/jun/19/open-source-revolution-conquer-one-percent-cia-spy) that received an unheard of 33,000 shares in three days, now up to 68,000 shares. This book identified over 60 "opens" and set the stage for a a broad global community discussion that has now agreed on nine major open source categories among which Open Software is one of the nine, documented at the P2P Foundation wiki page [Category:Open Source Everything](http://p2pfoundation.net/Category:Open_Source_Everything). I am now the foremost proponent for Open Source Everything Engineering (OSEE).

Comments on the Source Code initiative and other White House open source / open data / open government dabbling:

01 Too little too late. Lipstick on the pig. The digital innovators are nice people and mean well but everything they are doing is a joke on the margins.  They appear terrified of over-stepping their playpen's boundaries. Impacting on $80 billion within a $4 trillion budget is an effectiveness grade of 1% of 1%, at best -- and does nothing for the national economy or the global economy. As Dr. Russell Ackoff (May 2004) has said, "Stop doing the wrong things righter and do the right thing." 

02 OMB is incoherent and not paying attention. For example, the Director of OMB does not appear to have received his copy of the Memorandum on the need for an Open Source (Technologies) Agency that the US Postal Service has certified was delivered to the offices of the Vice President, the Secretaries of State and Defense, and the Administrator of the US Agency for International Development as well as the Director. What OMB **_should**_ be doing is rapidly processing this Memorandum as an inter-agency decision memorandum. The digital innovators are naive and inexperienced. One of them told me that "no new agencies" were desired by the President (whom I am sure he never sees). The very next day OPM announced a new agency to deal with security clearances. The Open Source (Technologies) Agency would be a path-finding and grant-making agency and could easily be managed with as few as 250 growing toward 1,200 at Full Operating Capability. It would lead to the eradication of the 50% waste that is endemic across all US policy domains (not just in government spending, but across the entire US economy) from agriculture to energy to health to housing to security to water.

03 I seek a meeting with the Director of OMB to discuss the two times previously that OMB senior officials have approved an Open Source Agency in principle, and to discuss advancing the Open Source (Technologies) Agency as an immediate Presidential initiative consistent with the Secretary of Defense D3 Innovation Summit objectives, and the President's varied intentions with respect to stabilizing and reconstructing the US economy and society so as to give the young and old and the unemployed hope. There is prior Congressional history -- Congressman Rob Simmons (R-CT-02) and I developed the Smart Nation - Safe Nation Act in one page, and if OMB desires, we can mobilize Congressman Simmons, now outside the Congress, to orchestrate an assured approval from the Republican controlled Congress for this new agency; it can also be, as NSA was, an executive agency funded by DoD under diplomatic auspices for its global engagement role but working intimately with every Cabinet office to achieve impact across all nine Opens in every policy domain. 

04 The proposed policies on open source code should be set aside. The new Open Source (Technologies) Agency should become the operational and policy authority, and would both enable massive adoption of open source software and hardware and spectrum enabling true open data, open decision-support, and open governance; and also absolute blockchain cyber-security for all government data and operations. No one in the US Government knows enough to be effective at regulating or promulgating Open Source Code, much less Open Source Everything Engineering (OSEE). All the knowledge needed to get this right and replicate what Vint Cerf did for the Internet is outside the USG. The Director of OMB has an opportunity to lead the creation of the Open Source (Technologies) Agency, and that in turn could become the engine for making the M in OMB a central aspect of how we govern going forward.  Hybrid governance is not a concept OMB understands yet, but it could become central to the M in OMB: harnessing the distributed intelligence of the Whole Nation (a phrase Mike Nelson borrowed from me for Al Gore to use in 1994), and bringing together academia, civil society, commerce, government, law enforcement. media, military, and non-government/non-profit in one seamless scalable exascale World Brain that practices holistic analytics conscious of true cost economics at every level across every domain. It's time for OMB to start MANAGING. The Open Source (Technologies) Agency is the engine for going forward.

05 OSEE costs one tenth of the financial cost of legacy approaches with their varied licensing, training, and maintenance fees. It also requires one tenth of the time, one tenth of the manpower, and ultimate yields a hundred-fold increase in inter-operability and scalability. In Europe open source is now standard for governments. At a strategic level OSEE is the only way the Sustainable Development Goals (SDG) can be achieved, in a fraction of the time at a fraction of the cost envisioned by the conventional donor financing and industrial technology approaches, and this in turn translates into making possible the President's call for a reduction of the Pentagon budget by 30% or more, while also empowering diplomacy, commerce, and development.

The time has come for the Director of OMB to think really big thoughts. We can have the Open Source (Technologies) Agency up and running within 30 days from Executive Order, fully-funded by DoD from within its existing budget, and this will translate into a public diplomacy, public relations, public interest, public benefits bonanza I would be glad to explain personally to the leadership of OMB before I leave for Europe on 16 April.

The original memorandum as delivered; as immediately translated into Chinese and then Spanish (Arabic and Russian and Iranian and Indonesian translations have been proposed); and as now refined and posted online, is attached.  A related reference is below. I would like very much to see this comment reach the Director of OMB, the only person in OMB with the responsbility and authority necessary to ingest and act on this comment in the public interest.
[D3 Innovation 1.8 CHINESE.docx](https://github.com/WhiteHouse/source-code-policy/files/183037/D3.Innovation.1.8.CHINESE.docx)
[D3 Innovation Memorandum 1.8.docx](https://github.com/WhiteHouse/source-code-policy/files/183036/D3.Innovation.Memorandum.1.8.docx)
[D3 Innovation Memorandum 2.1 SPANISH.docx](https://github.com/WhiteHouse/source-code-policy/files/183038/D3.Innovation.Memorandum.2.1.SPANISH.docx)
[D3 Innovation Memorandum 3.0.docx](https://github.com/WhiteHouse/source-code-policy/files/183039/D3.Innovation.Memorandum.3.0.docx)

[2016 Robert Steele: The Ultimate Hack – Resilient Villages, Smart Cities, Prosperous Nations at Peace — and Unlimited Clean Water](http:/www.phibetaiota.net/2016/03/2016-robert-steele-the-ultimate-hack-resilient-villages-smart-cities-prosperous-nations-at-peace-and-unlimited-clean-water/)

Robert David Steele
CEO, Earth Intelligence Network
http://robertdavidsteele.com

**Comment by johnmod3** [comment]
I don't see any specific comments on the policy?

**Comment by freephile** [comment]
^ Maybe you just didn't read it? There are 5 numbered comments.  To summarize and quote:  "Stop doing the wrong things righter and do the right thing."
