### ISSUE TITLE
Gov should never own any patents but may buy and public-domain them if needed

### ISSUE THREAD

**Issue by benrayfield** [WhiteHouse/source-code-policy#70]
This is related to source code because the legal ability to use it often depends on patents. Its debatable what rights opensource licenses give when they say you can use, modify, and distribute. Its my opinion that if a patent owner says you can use, modify, and distribute something which their patent describes, they need not mention patents since it is a logical dependency of what they offered. But usually opensource is not released by the relevant patent owners. We live under potential legal attack for many things we dont even know about. Most choose to ignore danger until its too late, investing our efforts into opensource that may not legally be usable.

A government is a process done for the people and should not be in business for its own profit, such as licensing its patents for money or saying who can and cant use them.

Also, as much of the world is angry at USA for various reasons, that could be improved by releasing all government owned patents to public-domain would help everyone and nobody would lose the ability to do what those patents describe.

A patent has 2 functions: To improve the reputation of inventors by proving they invented something, and to prevent others from using it by default, possibly allowing it in some cases.

Its great to know who invented things, but the other function of patents, to prevent others from using it, is not something governments should do. It is a selfish act, and we should want our government to be altruistic.

**Comment by royfielding** [comment]
Hence, the [Apache License 2.0](https://www.apache.org/licenses/LICENSE-2.0.html) and GPLv3.
