### ISSUE TITLE
Gather examples of similar, existing government policies

### ISSUE THREAD

**Issue by tbuckl** [WhiteHouse/source-code-policy#72]
For example, the government of Brazil has had an open-source policy for software procurement since 2003. It might be helpful to review the goals and effects of that policy.  @gilbertocamara has published several articles on the question may be a good source of information.

**Comment by chasingamy** [comment]
@tombuckley Thanks for sharing this with us! The team that developed this policy spoke with reps from other countries – including the United Kingdom and Canada – in regards to their own open source efforts. That said, we are always open to reviewing additional policies. Do you happen to have a link to the Brazilian Open Source Policy?

**Comment by melbamorph** [comment]
@tombuckley @parisj Here is an interesting overview posted on the Center for Strategic International Studies which lists governments which have implemented, or proposed, open source policies.  It was published in April of 2010. Not sure if there is a more recent version. The source page provides an explanation regarding how the report was compiled. The HTML version displays just the table. The PDF is the full report. 
- [HTML View](https://csis.org/publication/government-open-source-policies-0)
- [Full PDF Report](https://csis.org/files/publication/100416_Open_Source_Policies.pdf)
- [Source](https://csis.org/publication/government-open-source-policies)

I found the overview quite interesting and the list was longer than I imagined it would be.

**Comment by konklone** [comment]
India has also established an open source policy:
- http://deity.gov.in/content/policy-adoption-open-source-software-government-india-0
- http://tech.economictimes.indiatimes.com/news/technology/india-announces-open-source-policy-big-win-for-foss/46738776
- https://opensource.com/government/15/8/india-adopts-open-source-policy

**Comment by melbamorph** [comment]
Wow, @konklone,  they did that in 8 pages, double-spaced. I liked this quote from the last article: 

> Remarkably, there is little dispute about the policy itself. Rather, the central thrust of the attack is on the 'how to' of implementation.

I've had some questions about the implementation as well but not smart enough to figure out how to ask them intelligently yet. Just watching to see how this works. It's great to be able to watch the entire process in action.
