### ISSUE TITLE
Footnotes are out of sync between website and PDF

### ISSUE THREAD

**Issue by konklone** [WhiteHouse/source-code-policy#75]
As an example, footnote 26 on [Government-wide Code Reuse](https://sourcecode.cio.gov/Reuse/#fn26) is:

> As of the publication date of this policy, the most widely-recognized definition of “Open Source Software” – both in the U.S. and internationally – is provided by the Open Source Initiative, and provides 10 criteria that software must meet to be considered open source. This definition is accessible at https://opensource.org/osd

However, [in the PDF](https://sourcecode.cio.gov/SourceCodePolicy.pdf), footnote 26 is in section 5 and is "_See:_ https://petitions.whitehouse.gov/".

**Comment by chasingamy** [comment]
@konklone Thanks so much for catching this issue and for providing a starting point for figuring out where things went wrong. 

The PDF of the policy and the policy pages should now be completely synced up on footnotes -- please let us know if you find any other errors of this nature!
