### ISSUE TITLE
“Open Source Software” includes public domain software and requires clear international legal status

### ISSUE THREAD

**Issue by brittag** [WhiteHouse/source-code-policy#76]
_(I’m Britta Gustafson, a content designer at [18F](https://18f.gsa.gov), an office in the [U.S. General Services Administration](http://www.gsa.gov/) that provides in-house digital services consulting for the federal government. I’m commenting on behalf of 18F; we’re an [open source team](https://18f.gsa.gov/2014/07/29/18f-an-open-source-team/) and happy to share our thoughts and experiences. This comment represents only the views of 18F, not necessarily those of the GSA or its Chief Information Officer.)_

To help readers understand this policy (such as agency staff tasked with implementing it) and increase the public’s confidence that they can reuse government open source software without legal uncertainty, we recommend clarifying two aspects that are ambiguous in the current text:
1. The policy should consistently communicate that public domain software fits the definition of “open source software”.
2. The policy should require publicly-released code that is a U.S. “government work” (in the public domain in the U.S. by statute) to also have a clearly-stated open source license or public domain dedication for international use. This would make those works fit the definition of “open source software” internationally, which would help the public be certain they can reuse and contribute to those works.

Here are suggestions for how to clarify these parts.

**1) The policy should consistently communicate that public domain software fits the definition of “open source software”.**

Currently the draft policy isn’t quite consistent in its descriptions of “open source software”, “open source licenses”, and “public domain”. Licensing and copyright are complicated topics, and being precise will help readers understand the policy. The Open Source Initiative has [a good explanation of the legal complexities of “public domain” software](https://opensource.org/faq#public-domain), and it concludes that publicly-released “U.S. government work” public domain code (authored by federal employees as part of their job and public domain by statute) can be described as “open source software”.

To clarify in the **[Introduction](https://sourcecode.cio.gov/introduction/)**:
- “…additional benefits can accrue when code is also made available to the public as Open Source Software (OSS).”
  - This is the first mention of OSS in this policy, so it should be defined, especially since readers may come to the document with the common misconception that “open source” simply means “code that is visible to the public”. A way to do this would be to add the text of [footnote #23 from Government-Wide Code Reuse](https://sourcecode.cio.gov/Reuse/#fn23) as a footnote at the end of this sentence.
- **“Making code available with an OSS license** can enable continual improvement of Federal code projects…”
  - Some of this code will be released in the U.S. public domain (as U.S. government works), which is a form of OSS but isn’t “with an OSS license”. This bold part would be more clear as **“Making code publicly available as OSS”.**
- “…several Federal agencies and component organizations also have already begun publishing custom-developed code **under open source licenses or in the public domain…**”
  - Government software can be both in the U.S. public domain and under an open source license (internationally), which is a confusing but important fact to accommodate in these descriptions. It’d be more accurate and consistent to say “**as OSS (under open source licenses and/or in the public domain)**”.

To clarify in **[Objectives](https://sourcecode.cio.gov/Objectives/)**:
- “Establish requirements for releasing code **in the public domain or as OSS…**”
  - Code in the public domain is OSS, as it guarantees all the freedoms that open source licenses are designed to preserve. A more accurate way to phrase the bold part would be “**as OSS (in the public domain and/or under an open source license)**”.

To clarify in **[Federally Funded Custom Code as Open Source Software](https://sourcecode.cio.gov/OSS/)**:
- “…the Federal Government and partner organizations have recently begun using more OSS and publishing some of their custom software code **under open source licenses or in the public domain…**”
  - Since government software can be both in the U.S. public domain and under an open source license (internationally), it’d be more accurate to say “**as OSS (under open source licenses and/or in the public domain)**”.

To clarify in **[Definitions](https://sourcecode.cio.gov/Appendixa/)**:
- “A mixed source software solution may incorporate **public domain, open source, and/or proprietary code.**”
  - Since public domain code is open source code, this would be more accurate as “**open source (including public domain) and proprietary code**”.
- “…the term “proprietary software” refers to software that is typically subject to more disclosure restrictions than that which is released **as open source or in the public domain…**”
  - Similarly, since public domain software is open source software, it’d be more accurate to replace this bold part with “**as open source software**”.
- At the end of the definition of “Open Source Software (OSS)”:
  - To give readers a reference about the relationship between “public domain software” and “open source software”, add a sentence clarifying that this includes publicly-released public domain software: “OSS also includes software that is in the public domain and released publicly.” To help readers who need to understand this in detail, include a footnote that says “The Open Source Initiative provides an explanation of the complex topic of whether public domain software is open source software, with an assessment that “such software is effectively open source, or open source for most practical purposes”: [https://opensource.org/faq#public-domain](https://opensource.org/faq#public-domain)”

**2. The policy should require publicly-released code that is a U.S. “government work” (in the public domain in the U.S. by statute) to also have a clearly-stated open source license or public domain dedication for international use. This would make those works fit the definition of “open source software” internationally, which would help the public be certain they can reuse and contribute to those works.**

**A. Our recommendations**

Since the [statutory requirement](https://www.law.cornell.edu/uscode/text/17/105) for U.S. government works to be in the public domain only applies in the U.S., this policy should require that agencies include an open source license or public domain dedication (even for custom software developed in-house) for international audiences. This addition would help the draft policy achieve its stated goals; otherwise, for example, if an agency’s public code were public domain in the U.S. but copyrighted abroad, it wouldn’t be “open source software” according to the OSI definition or the definition in this policy’s appendix. U.S. government public domain works that do not state their international status can cause people to avoid reusing them due to legal uncertainty.

As a suggestion: the policy could maximize positive results by requiring agencies to include a public domain dedication for international audiences (for government works). That unified stance would simplify interoperability between open source projects from various agencies, and it would reduce the public’s confusion and maximize potential reuse. For example, if an agency publishes works that are in the public domain in the U.S. but GPLv3 internationally, that stance could be complex and confusing for other agencies with different preferred international licenses and members of the public who want to reuse and modify the code.

To avoid potential misunderstandings, Project Open Source should provide further guidance to make clear to agencies that they can’t apply an open source license to in-house work in a blanket way, because in the U.S. they cannot hold copyright on that work, and open source licenses are built on copyright — in other words, the agencies have no copyright interest with which to apply a license to that work. They should apply an open source license or public domain dedication for international audiences, and they should not apply an open source license for U.S. audiences.

**B. Our experiences**

As 18F, we address this legal landscape by adding [a standard LICENSE file to each 18F repository](https://github.com/18F/open-source-policy/blob/master/LICENSE.md). It has a notice of the work being in the U.S. public domain, and a [Creative Commons Public Domain Dedication (CC0 1.0)](https://creativecommons.org/publicdomain/zero/1.0/legalcode) for international use.

> As a work of the United States Government, this project is in the public domain within the United States. Additionally, we waive copyright and related rights in the work worldwide through the CC0 1.0 Universal public domain dedication…

This makes the legal status of 18F’s code as consistent as possible across all jurisdictions. 18F also requires any contractors or outside parties performing work on 18F’s properties to dedicate their contributions under CC0, to make the legal status of 18F’s code as consistent as possible regardless of its origin.

The Open Source Initiative [doesn’t recommend releasing software with CC0](https://opensource.org/faq#cc-zero), primarily due to concerns about its patent disclaimer, but we’ve assessed CC0 as the best available option to meet our need for a consistent worldwide public domain dedication. The [Consumer Financial Protection Bureau](https://cfpb.github.io/) also applies CC0 for worldwide use of its open source code. Project Open Source could provide guidance to help agencies choose the appropriate open source license or public domain dedication for worldwide use of their in-house government works.

**C. Example ways to implement these recommendations**

Here are examples of how these points could be integrated into the draft policy.

In **[Membership in the Open Source Community](https://sourcecode.cio.gov/OSS/)**, add another principle (this suggestion begins by copying the first sentence from **[Government-Wide Code Reuse](https://sourcecode.cio.gov/Reuse/)**):
- “Clear Legal Status – Under U.S. copyright law, all software created by Federal Government employees as a “government work” is in the public domain and, accordingly, is not subject to copyright protection in the United States.[20] Covered publicly-released software “government works” need to publicly state this U.S. public domain status. In addition, to make them meet the definition of open source software, they need to state a public domain dedication or open source license for worldwide use.”

Alternate version of that principle that would require international public domain: 
- “Clear Legal Status – Under U.S. copyright law, all software created by Federal Government employees as a “government work” is in the public domain and, accordingly, is not subject to copyright protection in the United States.[20] Covered publicly-released software “government works” need to publicly state this U.S. public domain status. In addition, to make them meet the definition of open source software, they would in theory need a public domain dedication or open source license for worldwide use. In practice, to make the legal status of these government works as consistent as possible across jurisdictions (which would maximize interoperability across agencies and maximize the ability of the public to adapt and contribute to them), these works need to state a public domain dedication for worldwide use.”

Edit: Updated footnote numbering (due to [this fix](https://github.com/WhiteHouse/source-code-policy/issues/75)).

**Comment by jonheller1** [comment]
Public domain and CC0 should not be encouraged.  They hardly even count as true Open Source software.

The description of the [Open Source Initiative's](https://opensource.org/faq#public-domain) conclusion is a bit misleading.  To quote directly from that page:  'What about software in the "public domain"? Is that Open Source? For most practical purposes, it is — sort of.'  They do not recommend it, and they especially do not recommend CC0.  I don't want "sort of" Open Source, I want the real thing.

I don't think the patent issues of CC0 can be so easily dismissed.  For example - can I re-use software built by 18F?  Does anybody own software patents on that code?  From a quick Google search it appears that several 18F employees have software patents.  Could I be sued for using some of that code?

There's little benefit of Open Source software if it's not clear that anyone can use it.  Almost none of the largest Open Source projects use public domain or CC0.  This policy should follow the lead of successful Open Source projects and avoid the public domain as much as possible.

**Comment by Scotchester** [comment]
@jonheller1 I am not an expert in patents, so I'll stay away from the subject of CC0 and international licensing, but work by government employees is, by law, public domain within the U.S.

What exactly is unclear about who can use work in the public domain?

The OSI, on the answer you quoted, even addresses our situation directly and says there is no issue:

> There are certain circumstances, such as with U.S. government works as described above, where it is not easy to apply a license, and the software must be released into the public domain. In these cases, while it would be inaccurate to display the OSI logo or say that the license is OSI-approved (since there is no license), nevertheless we think it is accurate to say that such software is effectively open source, or open source for most practical purposes, even though it is not officially released under an open source license. (This is assuming, of course, that in the laws of releasing jurisdiction the meaning of "public domain" is compatible with the Open Source Definition.) After all, the freedoms guaranteed by open source licenses are still present, and it is possible for the familiar dynamics of open source collaboration to arise around the software.

**Comment by jonheller1** [comment]
@Scotchester I'm not a lawyer but I think you're right that some work must be in the public domain.  My concern is that I don't want software to only be in the public domain unless absolutely necessary.

Software patents make it unclear who can use public domain software.  That is why the Open Source Initiative did not approve CC0.  Copyright, or a lack of copyright, is not sufficient if the code is covered by a patent.

This is why people have historically been concerned about Open Source code from some large companies like Microsoft.  There's nothing stopping them from releasing the source code and then later suing for patent infringement.  That is probably why some of their repositories include a separate patent promise.

Public domain and CC0 are not good enough to keep software free.

**Comment by brittag** [comment]
For reference, [here’s the section of U.S. copyright law](https://www.law.cornell.edu/uscode/text/17/105) that says U.S. “government works” can’t be copyrighted:

> Copyright protection under this title is not available for any work of the United States Government, but the United States Government is not precluded from receiving and holding copyrights transferred to it by assignment, bequest, or otherwise.

The U.S. government is in an interesting situation different from most organizations and companies that publish open source work: it needs to reflect U.S. laws that apply to government work, as well as reflecting the principles of free and open source software.

If a “government work” were public domain in the U.S. (by law) and had GPLv3 applied for international use, in practice people everywhere are likely to treat that work as simply a GPLv3 work. Legal jurisdictions are complicated, and most people would prefer to avoid accidentally violating the government’s GPL license, so even U.S. individuals and companies would probably treat this as a GPL work rather than as a public domain work. In practice, this dual status would interfere with the ability of people in the U.S. to use government works as un-copyrighted works.

International public domain dedications help ensure that people in the U.S. can use government works as works unprotected by copyright as established by law.

Ambiguous patent status could be handled by adding language about patents along with public domain dedications.

**Comment by johnmod3** [comment]
NASA (DOE?) does have the right to copyright. Maybe assign all code to NASA and have them make OSS

**Comment by brittag** [comment]
As potential supplemental references for explaining that publicly-distributed public domain code is open source software/free software, the Free Software Foundation also maintains reference material about this:
- ["Categories of free and nonfree software"](http://www.gnu.org/philosophy/categories.en.html) includes public domain software (with source) in its chart of free and open source software.
- [List of software licenses](http://www.gnu.org/licenses/license-list.html) provides a definition of public domain software, which includes that it’s functionally equivalent to a very permissive OSS/FOSS license: "Being in the public domain is not a license; rather, it means the material is not copyrighted and no license is needed. Practically speaking, though, if a work is in the public domain, it might as well have an all-permissive non-copyleft free software license."

**Comment by royfielding** [comment]
Sorry, this issue is seriously misleading.  Public domain code is effectively open source because it has no owner that has exclusive rights to copy. However, that does not make CC0 an open source license. CC0 specifically excludes other intellectual property rights that can ALSO be used to restrict distribution and use of the software. It is not an open source license for that reason, regardless of the comments that OSI made regarding public domain in general.

The policy should not claim things that simply aren't true. Public domain does not fit the definition of open source software -- it just doesn't conflict with any open source license. It doesn't help to say that something which isn't true. What we should be saying is that the government-created work is public domain (with NO REFERENCE TO CC0) and may also be redistributed and used under ANY open source license. This eliminates the need to craft yet another license and ensures that the effective license is open source wherever the public domain designation fails.

It does not quite satisfy the need for a contributor license on incoming (non-government) contributions, but that is a different issue.
