### ISSUE TITLE
The Justice Argument for "Open by Default"

### ISSUE THREAD

**Issue by RobertLRead** [WhiteHouse/source-code-policy#83]
More and more policy is implemented with computer technology, or at least supported by it. Until proven otherwise, we should therefore assume that computer software has the potential to impact the fair execution of governmental function, and should therefore be transparent.

Consider the separate case management software systems used by the Social Security Administration, the IRS, and the Department of Labor. A software defect:
-  ...in the Social Security Disability System might cause cases to be misadjudicated, or even adjudicated with bias based on the nature of the disability or the geographic region or race of the applicant.
- ...in the IRS software might statistically compute overcharges for one group or class of firms.
-  ...in a Fair Labor Standards Act investigation of the Department of Labor might prejudicially emphasize or lose important evidence for or against a firm.

In these cases, it is easy to see that the affected classes, firms, or individuals have a civil right to examine the code upon which their equal access to government services or justice depends. A numeric target based on expediency or economic decisions within an agency is unlikely to provide satisfactory transparency for whatever fraction of the total software of the government should be open for the purpose of providing due process and protection from vague laws.

> The Supreme Court of the United States interprets the [Due Process] Clauses [of the 5th and 14th Amendments] as providing four protections: **procedural due process** (in civil and criminal proceedings), substantive due process, a prohibition against **vague laws**, and as the vehicle for the incorporation of the Bill of Rights.

-- Quoted from the Wikipedia article on Due Process: https://en.wikipedia.org/wiki/Due_process#United_States (emphasis and clarifications mine).

It seems likely the Congress in 2016 now writes or will write laws such as "The Department of Homeland Security shall make a no-fly database", or "The Veterans Administration shall compensate Veterans fairly based on an algorithm which computes the severity of their disability", or "NIST is authorized to write recommendations and policy around the use of biometric data for security pertaining to X"
which imply the creation of software without specifying all of the details of that software. Therefore, as part of the prohibition against "vague laws" the American citizen has a right to review those extensions of the law embodied in software.

In the case of criminal justice, the Confrontation Clause of the 6th Amendment gives a defendant a right to cross-examine evidence presented against them, and in 2016 that means all evidence **computed** against them. This is best accomplished by simply making the code open to all to review. Although most individuals and firms do not have the technical competence to review computer source code, they may be able to hire someone to assist them or get assistance from civil rights organizations. For a relevant actual example in which lives are at stake see: (New Protocol Leads to Reviews of "Mixed DNA" Evidence https://www.texastribune.org/2015/09/12/new-crime-lab-protocol-forcing-review-dna-evidence/)[https://www.texastribune.org/2015/09/12/new-crime-lab-protocol-forcing-review-dna-evidence/] which begins: 

> "This past spring, the FBI notified crime labs there were errors in the data used to calculate the chances that DNA found at a crime scene matched an individual."

"Open by Default" is vastly better than a numeric target when viewed from the point of view of providing equal access to justice, equal protection under the law, due process, and prohibition from vague laws. If a policy of "Open by Default" cannot be achieved then any software which affects the "due process" treatment of individuals or firms should be made OSS, subject to security exceptions already explicit in the policy proposal.

**Comment by freephile** [comment]
Going even further than 'Open', I propose that "Free (as in Freedom) by default" is necessary to provide equal justice under the law. https://github.com/WhiteHouse/source-code-policy/pull/78

**Comment by pikurasa** [comment]
agreed.
