### ISSUE TITLE
It should be free software, not open source.

### ISSUE THREAD

**Issue by RLVogel** [WhiteHouse/source-code-policy#84]
Default for government developed, taxpayer paid, software should be free software, licensed under "GPLv3 or later".  The 20% rule is arbitrary. Instead, the GPL should be applied unless there is a compelling reason to with-hold the product from the public.

**Comment by freephile** [comment]
I created a pull request which implements an updated policy whereby all references to 'Open Source' are replaced by 'Free Software' https://github.com/WhiteHouse/source-code-policy/pull/78

**Comment by johnmod3** [comment]
Free Open Source Software ( FOSS ) is more the industry standard

**Comment by freephile** [comment]
Industry does indeed like to de-emphasize the "libre" aspect.  It's a shame that in the "land of the free", there aren't popular, unique adjectives that equate to 'freedom'. I can think of unencumbered, liberated, emancipated, unfettered.  Other languages have libre, so we borrow it.  But it's still a mouthful.  https://en.wikipedia.org/wiki/Libre_(word)
