### ISSUE TITLE
Minimize documentation requirements for open source projects

### ISSUE THREAD

**Issue by brittag** [WhiteHouse/source-code-policy#85]
_(I’m Britta Gustafson, a content designer at [18F](https://18f.gsa.gov), an office in the [U.S. General Services Administration](http://www.gsa.gov) that provides in-house digital services consulting for the federal government. I’m commenting on behalf of 18F; we’re an [open source team](https://18f.gsa.gov/2014/07/29/18f-an-open-source-team/) and happy to share our thoughts and experiences. This comment represents only the views of 18F, not necessarily those of the GSA or its Chief Information Officer.)_

Based on our experiences publishing [400+ public repositories](https://github.com/18F?utf8=%E2%9C%93&query=+only%3Asources+only%3Apublic+) over the past two years, we recommend trimming the list of open source project README requirements at “f. Documentation” in [5.2 Membership in the Open Source Community](https://sourcecode.cio.gov/OSS/#5-2-membership-in-the-open-source-community) to just a description of the project (which could be brief) and license details.

All of the listed components are thoughtful ideas and could be very helpful for potential people interested in contributing to or reusing government projects, but we suggest listing the rest as recommendations in Project Open Source instead of as requirements in the policy. Our reasons:
- When this policy is finalized and agencies begin implementing it, OMB and agencies will learn a lot about effective open source project management through real life experience, and it’ll be helpful to be able to quickly iterate on these documentation requirements. Listing detailed requirements in the policy is risky — it means the policy can’t respond to real-world experiences in a flexible and agile way. Writing good documentation requires iterating a lot based on user needs and user testing, like good software development, and these components are good ideas but seem to be untested at a large scale.
- We believe these documentation requirements wouldn’t flexibly accommodate the wide variety of open source projects that get released in government. For example, some of our open source repositories are tiny three-hour experiments (which don’t need careful documentation), while some others are components of large complex projects with many interrelated repositories (where each README may be just a brief description and a link to a documentation website that explains the whole project).
- In our view, a poorly documented open repository is much better than no open repository at all. (Compared to a closed repository, an open repository with little documentation would still increase transparency and potential opportunities for discovery and collaboration.) The policy’s goals include encouraging more agencies to release more open code, so we suggest avoiding adding labor burdens to open code that aren’t required for closed code.
- Requiring extensive per-repository information would be difficult for OMB to enforce across agencies, and for agencies to enforce across their offices.

**Comment by zaksoup** [comment]
I'm Zachary Auerbach, a software engineer at Pivotal, and for the last year I've been working on Open Source Cloud Foundry, the project that currently powers cloud.gov

I agree with @brittag and would like to further stipulate that, wherever possible, code can and should serve as documentation.

For example: providing a `./configure` script which downloads and installs dependancies as needed is a much better experience than documenting dependencies explicitly in the README. In this case the developer only needs to document that `./configure` will install dependencies. Developers will use this script in the course of their work on the repo and CI will use it to prepare for running tests/deploying, so issues with it will quickly be noticed. Users can read the script to see what dependencies are installed. Furthermore, the documentation never lies to users, as is possible in the case where a developer adds a dependency but forgets to add it to the README.

Taking opportunities to turn documentation into code allows developers of a repo to reduce the chance that their documentation lies to consumers.

**Comment by neilernst** [comment]
_I'm Neil Ernst, working at the Software Engineering Institute and occasional instructor of a course on software architecture documentation.  These are my views._

The proposed OMB regulation suggests documentation needs at a minimum:

> 1. The status of the software (e.g., prototype, alpha, beta, release, etc.);
> 2. The intended purpose of the software;
> 3. Expected engagement level (i.e., how frequently the community can expect to be engaged by the agency);
> 4. License details; and
> 5. Any other relevant technical details on how to build, make, install, or use the software, including library dependencies (if applicable).

These don't seem onerous. They definitely aren't suggesting compliance with (e.g.) [ISO42010](https://en.wikipedia.org/wiki/ISO/IEC_42010). In fact apart from (5) they seem to be exactly what @brittag is suggesting. 

In an ideal world "read the ./config script" would be acceptable. Unfortunately, even capable developers have [trouble figuring out build scripts](http://dl.acm.org/citation.cfm?id=1985813), and the developer who will not write a Readme is unlikely to take the time to provide a useful and working installation script. I'm not sure  I agree that "a poorly documented open repository is much better than no open repository at all". If a repository is undocumented and unusable, is it worth releasing it? Shouldn't the public demand better from their agencies?

Even ecosystems with package managers (Python, for example), can be insanely complex to get working, hence a call for [installation-driven development](http://www.third-bit.com/2016/03/19/continuous-installation-checking.html). I think at a minimum the released project needs to make it clear how an average user (not ex-Googlers, for example) would be able to get the thing working.

**Comment by jawz101** [comment]
I have yet to be able to install VistA on a box so I agree with @zaksoup that an installation procedure should be a minimum requirement (along with sample input and output.)  If a public repository cannot provide code that is reproducible than it probably isn't worth belonging in this 20% public domain code.  The notion that a poorly documented open repository is better than no open repository at all craters open source projects.  Hopefully projects that do end up in the repo contain sufficient documentation to the extent in which public contributors can offer translations in other languages.  That's when software starts growing on its own.

Regardless, this is a fantastic stepping stone and I'm glad this is at least being implemented in some fashion.  Hopefully this comes with OAUTH and wikis so more people can feel comfortable to contribute.

**Comment by frankjosephbarbato** [comment]
I must agree with Nell Ernst. I don't think the minimal requirements are onerous. Developers have a tendency to rewrite and any documentation that can be provided will definitely encourage its reuse.
