### ISSUE TITLE
Open Standards, Open Interoperability if not Open Source

### ISSUE THREAD

**Issue by henryweimd** [WhiteHouse/source-code-policy#88]
Well-intentioned intelligent people will argue for open source; sometimes this is not possible, as in the world of electronic health records.  In those cases, private companies may either intentionally or inadvertently create barriers for interoperability with 3rd party software or for data to flow freely to other systems.  

In the case of healthcare, this data blocking has become a major issue for HHS ONC to wrestle down.  Sometimes it a problem caused by software design without well-articulated external APIs based on open standards.  Other times it is a problem of the complexity of implementation of the software, creating burdensome and vendor-locking scenarios where the free market may not deliver the best value for taxpayer, but rather a vendor may remain in place due to the high switching costs for any arm of the government.

So rather than open source, please consider federal IT strategy -- either directly-developed or procured -- that may revolve around open standards to permit a free, competitive market to operate and deliver the best and most affordable solutions for taxpayers.

**Comment by rafael5** [comment]
This  is a confusing argument.  It conflates code and data. Of course regulation will require the security of data. In the case of patientn data, that is what HIPAA is for.  

We don't want to water down the message, loud and clear:

Code = published.  100%.  By default. On Github  =  Open Source.

And separately:

Data = secured.

**Comment by int19h** [comment]
They are two orthogonal issues. The code should be open, _and_ all the standards, protocols, data formats etc used in said code should be publicly documented. In cases where code cannot be open sourced because an exemption applies, the open interoperability part should remain in force (or a separate exemption should be thought for it, with its own rationale).
