### ISSUE TITLE
Acknowledge “free software” in the policy

### ISSUE THREAD

**Issue by brittag** [WhiteHouse/source-code-policy#92]
_(I’m Britta Gustafson, a content designer at [18F](https://18f.gsa.gov/), an office in the [U.S. General Services Administration](http://www.gsa.gov/) that provides in-house digital services consulting for the federal government. I’m commenting on behalf of 18F; we’re an [open source team](https://18f.gsa.gov/2014/07/29/18f-an-open-source-team/) and happy to share our thoughts and experiences. This comment represents only the views of 18F, not necessarily those of the GSA or its Chief Information Officer.)_

The term “open source software” is closely related to the term “free software” and [usually means the same thing in practice](http://www.gnu.org/philosophy/categories.en.html), but rather than being neutral and interchangeable terms, these are complex terms that come bundled with more than 30 years of software history and culture (often collectively referred to as “[free and open-source software](https://en.wikipedia.org/wiki/Free_and_open-source_software)”).

The draft policy seems to use “open source software” as shorthand to mean “free and open-source software”, rather than using it as a way of intentionally taking a stand on the philosophies embedded in these terms.

It makes sense for this policy to primarily use the term “open source software” because that’s clear and succinct (rather than saying “free and open-source software” or “FOSS” many times), but the policy should also note that it intends “open source software” simply as shorthand for “free and open-source software.” This way, the text of the policy will more clearly reflect the intent of the policy for readers who are familiar with these terms.

For example, in [Appendix A: Definitions](https://sourcecode.cio.gov/Appendixa/), the definition of "Open Source Software (OSS)" could be revised to say:

> **Open Source Software (OSS)**: Software that can be freely accessed, used, changed, and shared (in modified or unmodified form) by anyone. OSS is often distributed under licenses that comply with the definition of “Open Source” provided by the Open Source Initiative ([https://opensource.org/osd](https://opensource.org/osd)).[50] The term “free software” (with “free” as in “freedom”) is also commonly used to describe software that allows these uses ([http://www.gnu.org/philosophy/free-sw.en.html](http://www.gnu.org/philosophy/free-sw.en.html)); in this policy, “open source software” (OSS) is used as a synonym for “free and open-source software” (FOSS).

**Comment by bassdeal** [comment]
I agree with brittag on the post above that it is necessary to tie this policy to a solid definition of open and free software.  My fear of using the term "Open Software" alone invites legal interpretations which could dilute or even nullify the intent of this policy.  The current numerous  "Open Source" licenses in existence and the great variance of their use in respect to allowing or restricting continued public use (i.e. level of commercialization and restrictions on derived works) demonstrates the need to tie this policy to a solid definition of free software.  The cited GNU reference above is good as is the GPLv3 license (http://www.gnu.org/licenses/gpl-3.0.html).

**Comment by pikurasa** [comment]
I agree. This is addressed in basic way with https://github.com/WhiteHouse/source-code-policy/pull/78
